texts.complexus = {};
if(!texts.treatises) texts.treatises = [];
texts.treatises.push("complexus");
texts.complexus.exportYear = 2024;
texts.complexus.exportMonth = 4;
texts.complexus.exportDay = 12;
texts.complexus.exportHour = 9;
texts.complexus.exportMinutes = 37;
texts.complexus.sources = [];
texts.complexus.edited = 'Complexus effectuum musices\n\
Editor: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 22 March 2024\n\
Base file:\n\
Sources:\n\
Br1	B-Br II 4147 mus., fols. 125ra-127va (incomplete)\n\
G	B-Gu 70, fols. 74ra-77vb (modern numeration)\n\
edC	Scriptorum de musica medii aevi nova series a Gerbertina altera, 4 vols., ed. Edmond de Coussemaker (Paris: Durand, 1864–76; repr. Hildesheim: Olms, 1963), 4: 191b–195a (Br1), 195a–200b (G)\n\
edS	Johannis Tinctoris Opera theoretica, ed. Albert Seay, 3 vols. in 2, Corpus scriptorum de musica, 22 (n.p.: American Institute of Musicology, 1975–8), 2: 165–77\n\
edZ	Luisa Zanoncelli, Sulla estetica di Johannes Tinctoris: con edizione critica, traduzione e commentario del Complexus effectuum musices, Studi di teoria e estetica della musica ([Bologna]: Arnaldo Forni, 1979), 74–115\n\
<treatise>\n\
<title>Complexus {var=(ins.) "viginti" G} effectuum {var=(ins.) "nobilis artis" G} musices: {var="editus a magistro {var="Joanne" (ed.) : "Johanne" Br1} Tinctoris, in legibus licentiato regis{ }que Sicilie capellano" Br1 : "sic enim eam vocat Aristoteles 8º <citation>Politicorum</citation>, quam Plato ceterarum artium “potentissimam”, Quintilianus “pulcherrimam”: sed Augustinus “divinam” appellat scientiam, tum rationibus tum sacris auctoritatibus, tum philosophorum historicorum ac poetarum dictis: que Cicerone teste peti solent ad faciendam fidem vallatus.**NB: this addition to the title in G is abridged from the Prologue (Prol.7, 6, 9), which is omitted as such. G gives Tinctoris’s name and offices in the <italic>explicit</italic>, drawing also on Prol.2.**" G}</title>\n\
<prologue>\n\
<heading>Prologus</heading>\n\
Illustrissime domine Beatrici de Aragonia, regis Sicilie, {var="Hierusalem" (ed.) : "Jherusalem" Br1} et Ungarie probissime filie, {var="Joannes" (ed.) : "Johannes" Br1} Tinctoris, inter legum artium{ }que mathematicarum professores minimus, immortalem servitutem. Scienti mihi, beatissima Beatrix, quam ardenti quam{ }que vehementi studio ingenue arti musices operam impendas, occurrit quosdam ingentes effectus ipsius compendiose tue celsitudini exponere. Quibus (licet animum tuum, instar illius a quo celestem duxit originem, arbitrer constantissimum) exciteris nunquam abs tam insigni opera desistere. Quod quidem aggressus ego sum non minus amore tui quam artis inductus. Enimvero ut quam gratissimum mihi est musicen, cui me ab ineunte etate dedidi, studio tam illustris, tam prudentis tam{ }que formose domine regie filie gloriosissimam fore, sic et beneficio ipsius artis quam ceterarum “potentissimam” Plato,**Quotation not found. Not Plat. Rep. III.401D, where Ficino’s translation (the only one that could have been available to Tinctoris) has “Ob hanc igitur causam, inquam ego, o Glauco, ex ipsa <italic>principali</italic> in musica educatione rhythmus et harmonia interiora animi subeunt feriuntque <italic>vehementissime</italic> animum” (emphasis added).** “pulcherrimam” Quintilianus,**Quint. Inst. I.x.17.** “divinam”{ }que scienciam Augustinus asserit,**August. De mus. I.ii.3: “divina ista disciplina”.** tuum semper animum ab omni dolore purificatissimum expeto. Ne{ }que me credas velim omnes effectus ipsius “liberalis ac honeste” musices (sic eam Aristoteles vocat)**Aristot. Pol., trans. G. de Moerbeke, 1338a32 (VIII.iii.1).** hoc in opusculo complecti, verum tantummodo viginti, ut sunt:\n\
<table>\n\
{¶ } Deum delectare;\n\
   Dei laudes decorare;\n\
{¶ } Gaudia beatorum amplificare;\n\
   Ecclesiam militantem triumphanti assimilare;\n\
{¶ } Ad susceptionem benedictionis divine preparare;\n\
   Animos ad pietateum excitare;\n\
{¶ } Tristiciam depellere;\n\
   Duriciam cordis resolvere;\n\
{¶ } Dyabolum fugare;\n\
   Exstasim causare;\n\
{¶ } Terrenam mentem elevare;\n\
   Voluntatem malam revocare;\n\
{¶ } Homines letificare;\n\
   Egrotos sanare;\n\
{¶ } Labores temperare;\n\
   Animos ad prelium incitare;\n\
{¶ } Amorem allicere;\n\
   Iocunditatem convivii augmentare;\n\
{¶ } Peritos in ea glorificare;\n\
   Animas beatificare.\n\
</table>\n\
Quos quidem admirabiles et (ut ita dicam) divinos effectus tum rationibus, tum auctoritatibus sacris, tum philosophorum, {var="historicorum" (edS) : "hystoricorum" Br1} ac poetarum dictis (que Cicerone teste peti solent “ad faciendam fidem”)**Cic. Top. xx.78: “sed et oratores et philosophos et poetas et historicos, ex quorum et dictis et scriptis saepe auctoritas petitur ad faciendam fidem”.** comprobare decrevi ac ordine debito de quolibet ut liquidius pateant disserere institui. Et huic licet editioni, eo quod ardua sit, tum theologiam, tum philosophiam, tum poesim concernens, ingenium cantoris impar agnoscas, haud me vicii presumptionis profecto accusabis, si non ignores in ardua tendere proprium esse virtutis.\n\
</prologue>\n\
<chapter>\n\
<heading>{var="De primo effectu musice. Capitulum {var=".i." edC : "1^m" Br1}" Br1 : "Effectus primus est iste." G}</heading>\n\
{var="Primo" Br1 : (om.) G}: Musica Deum delectat.**Cf. De inv. et usu I.v, “Primo”.** {¶ } Proprium etenim est cuiuslibet artificis suo delectari artificio, maxime dum id perfectum fuerit. Unde {var="quom" (ed.) : "cum" Br1 G} Deus, qui “opus imperfectionis non novit” (ut habetur in capitulo “Maiores”, “De baptismo et eius effectu”, <citation>Extra</citation>),**Decr. Greg. IX III.xlii.3 (ii.646 Friedberg).** in antiquis hanc artem perfectissimam operatus fuerit, tenendum est quod ab ea preceteris delectatur. Hinc a dilectissima {var="sponsa sua" Br1 : "sua sponsa" G} (quam fideles Ecclesiam credunt) optat dulcedinem vocis audire, quam sola musica {var="potest efficere" Br1 : "efficere potest" G}. Quippe per Salomonem, Canticorum {var="secundo capitulo" Br1 : "2º" G}, sic {var="alloquitur illam" Br1 : "illam alloquitur" G}: “sonet vox tua dulcis in auribus meis”, et sequitur, “vox enim tua dulcis”,**Cant. 2:14.** quasi dicat, “Eo quod vox tua dulcis (idest melodiosa) sit, opto ut sonet in auribus meis.” Neque vocis dulcedinem audire Deus optaret, si eum quovismodo non delectaret.\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De secundo effectu. Capitulum {var=".ii." edC : "2^m" Br1}" Br1 : "Sequitur Secundus effectus." G}</heading>\n\
{var="Secundo" Br1 : (om.) G}: Musica laudes Dei decorat.**Cf. De inv. et usu I.v, “Secundo”.** Hinc in Ecclesia triumphanti, perpetuis Dei laudibus insistentetes, eas quo magis decorentur cantare dicuntur. Unde {var="Joannes" (edC^2) : "Johannes" Br1 G} in Apocalipsi capitulo {var="quartodecimo" Br1 : "14º" G} refert vocem {var="cantantium" G : "cantancium" Br1} “quasi canticum novum ante sedem” Dei fuisse, “sicut {var="citharedorum" (ed.) : "cytharedorum" Br1 G} {var="citharizantium" (ed.) : "cytharizantium" Br1 : "chitharisantium" G} in {var="citharis" (ed.) : "cytharis" Br1 G} suis”.**Apoc. 14:3, 2.**\n\
Hinc {var="Virgilius" Br1 : "Vergilius" G} fingit eos qui erant in Campo {var="Elysio" Br1 : "Heliseo" G} laudes {var="Apollinis" Br1 : "Appollinis" G} sapientie dei canere. Nam in {var="sexto" Br1 : "6º" G} libro <citation>Eneidos</citation> de Enea, qui cum sibilla in illum locum devenerat, ita dicit:\n\
<verse>Conspicit, ecce, alios dextra leva{ }que per herbam<l/>{var="vescentes" Br1 G : "vescentis" (Virg.)} letum{ }que choro peana {var="canentes" Br1 G : "canentis" (Virg.)}.**Virg. A. VI.656–7.**</verse>\n\
Sacerdotes etiam sub Evandro more Archadico deo Herculi laudes in decorem canebant, de quo idem Virgilius in octavo sic inquit:\n\
<verse>{var="Tunc" Br1 G : "Tum" (Virg.)} Salii ad cantus {var="incensa" Br1 (Virg.) : "intensa" G} altaria circum<l/>populeis assunt evincti tempora ramis,<l/>hic iuvenum chorus, ille senum; qui carmine laudes<l/>Herculeas et facta ferunt: ({var="et cetera" Br1 : (om.) G})**Virg. A. VIII.285–8.**</verse>\n\
Numa{ }{var="que" Br1 : (om.) G} Pompilius, sacrorum romanorum piissimus institutor, voluit Salios laudes deorum musicis decorare versibus. Unde Quintilianus {var="in" Br1 : (om.) G} libro primo <citation>Institutionum oratoriarum</citation>: “Versus quoque Saliorum {var="carmen habent" Br1 G : "habent carmen" (Quint.)}.”**Quint. Inst. I.x.20.**\n\
Sed hec ad falsam religionem pertinent. Rex autem David, vere religionis cultor, Dei laudes decorari cupiens, cantores instituit qui coram archa federis illas decantarent, de quo Ecclesiastici capitulo {var="quadragesimoseptimo" Br1 : "47º" G}: “stare fecit cantores {var="iuxta" Br1 G : "contra" (Vulg.)} altare, et in sono eorum dulces fecit {var="modulos" Br1 G : "modos" (Vulg.)}.”**Eccli. 47:11.** Hinc ille, ab omnibus variis instrumentis musicis Dei laudes decorari expetens, postquam dixit in Psalmo {var="centesimoquadragesimosexto" Br1 : ".Cxlvj.º" G}, “Deo nostro sit iocunda decora{ }que laudatio”,**Ps. 146:1c.** subiungit in ultimo,\n\
<verse>Laudate eum in sono tube;<l/>laudate eum in psalterio et {var="cithara" G : "cythara" Br1}.<l/>Laudate eum in tympano et choro;<l/>laudate eum in cordis et organo.<l/>Laudate eum in cymbalis bene{ }sonantibus;<l/>laudate eum in cymbalis iubilationis.<l/>Omnis spiritus laudet Dominum!**Ps. 150:3–6a.**</verse>\n\
Instar cuius regie institutionis Ambrosius primum in Ecclesia militanti laudes Dei musica decorari ordinavit.**Cf. August. Conf. IX.vii.15: “Tunc hymni et psalmi ut canerentur secundum morem orientalium partium, ne populus maeroris taedio contabesceret, institutum est, ex illo in hodiernum retentum multis iam ac paene omnibus gregibus tuis et per cetera orbis imitantibus.” Cf. Th. Aq. S. theol. II^a^-II^ae^ q. 91 a. 2 s.c. (article cited in chap. viii below).** Quo effectum est ut hac tempestate prestantissimi inveniantur cantores Dei laudibus accuratissime vacantes; quorum quidem cantorum tanto prestantius est officium {var="quantum" Br1 : "quanto" G} Deus, cui cantando devote serviunt, {var="rebus" Br1 : "tribus" G} ceteris prestat.\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De {var="tertio" edC : "tercio" Br1} effectu. Capitulum {var=".iii." edC : "3^m" Br1}" Br1 : "Tertius effectus est." G}</heading>\n\
{var="Tertio" edZ : "Tercio" Br1 : (om.) G}: Musica gaudia beatorum amplificat.**Cf. De inv. et usu I.v, “Tertio”.** Credimus enim {var="beatitudinem" Br1^c G : "beatidudinem" Br1^*} esse statum omnium bonorum aggregatione perfectum; quam si beati sint assequuti delectabilissima que bona sunt eis deesse non possunt. Unde {var="quom" Br1 : "cum" G} (ut inquit Philosophus in {var="octavo" Br1 : "8º" G} <citation>Politicorum</citation>) musica sit “delectabilissimorum”,**Aristot. Pol., trans. G. de Moerbeke, 1339b20 (VIII.v.2).** quod {var="musicarum" Br1 : "musicalium" G} concordiarum dulcedo gaudia eorum amplificet ratione {var="concludimus" G : "9clu-di^9 [concludius]" Br1}. Hinc, quoniam felicitatem animorum beatorum instrumenta musica significant (ut patet per Ovidium in {var="quarto" Br1 : "4^t^o" G} <citation>Methamorphoseos</citation> ita dicentem: “{var="lyre" edS : "lire" G}{ }que / {var="tibia" Br1 : "tibie" G}{ }que et cantus, animi felicia leti / argumenta, sonant”**Ov. Met. IV.760–62.**), pictores{var=(ins.) "etiam" G}, quando beatorum gaudia designare volunt, angelos diversa instrumenta musica concrepantes depingunt. Quod {var=(ins.) "quidem" G} Ecclesia non permitteret nisi gaudia beatorum musica amplificare crederet.\n\
Nec extra propositum Virgilius gaudiis Camporum {var="Elysiorum" Br1 : "Heliseorum" G}, que “{var="amena vireta, locos letos, fortunata nemora" Br1 G : "locos laetos et amoena virecta / fortunatorum nemorum" (Virg.)} sedes{ }que beatas” appellat, musicam interesse finxit. Unde in {var="sexto" Br1 : ".vj.º" G} libro <citation>Eneidos</citation>, de {var="his" (ed.) : "hiis" Br1 G} que in illis campis congaudebant, hec {var="inquit" Br1 : "ait" G}:\n\
<verse>pars pedibus plaudunt choreas et carmina dicunt.<l/>Necnon {var="Traicius" G : "Traycius" Br1} cum longa veste sacerdos<l/>obloquitur numeris septem discrimina vocum;<l/>iam{ }que eadem digitis, iam pectine pulsat eburno.**Virg. A. VI.638–9, 644–7.**</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De quarto effectu. Capitulum {var=".iv." edC : "4^m" Br1}" Br1 : "Quartus effectus est." G}</heading>\n\
{var="Quarto" Br1 : (om.) G}: Musica Ecclesiam militantem triumphanti assimilat.**Cf. De inv. et usu I.v, “Quarto”.** Unde {var="Bernardus" Br1 : "Barnardus" G} super Cantica: “nihil {var="in terris ita representat quendam" Br1 G : "ita proprie quemdam terris repraesentat" (Bern.)} celestis habitationis statum sicut alacritas laudantium Deum”.**Bern. Clar. Serm. in Cant. XI.i (PL clxxxiii.824B).** Pro quo facit Augustinus, ita dicens in capitulo {var="quartodecimo" Br1 : "14º" G} decimiseptimi libri <citation>De civitate Dei</citation>: “Diversorum {var=(ins.) "enim" (August.)} sonorum rationabilis moderatus{ }que concentus concordi varietate compactam bene ordinate civitatis {var="Dei" Br1 G : (om.) (August.)} insinuat unitatem.”**August. De civ. XVII.xiv.3.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De quinto effectu. Capitulum {var=".v." edC : "5^m" Br1}" Br1 : "Quintus effectus est." G}</heading>\n\
{var="Quinto" Br1 : (om.) G}: Musica ad {var="susceptionem" G : "suscepcionem" Br1} benedictionis {var="divine" Br1 : "Domini" G} preparat.**Cf. De inv. et usu I.v, “Quinto”.** Unde {var="Quarti" Br1 : "4º" G} Regum {var="tertio" edC : "tercio" Br1 : "3º" G} capitulo: “{var="Quom" (ed.) : "Cum" Br1 : "Dum" G : "Cumque" (Vulg.)} caneret psaltes, facta est super {var="Eliseum" (ed.) : "Elyseum" Br1 : "Heliseum" G : "eum" (Vulg.)} manus Domini”.**4 Reg. 3:15b.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De sexto effectu. Capitulum {var=".vi." edC : "6^m" Br1}" Br1 : "Sextus effectus est." G}</heading>\n\
{var="Sexto" Br1 : (om.) G}: Musica animos ad pietatem excitat.**Cf. De inv. et usu I.v, “Sexto”.** Unde Augustinus in libro decimo <citation>Confessionum</citation>: “adducor {var=(ins.) "non quidem inretractabilem sententiam proferens" (August.)} cantandi consuetudinem approbare in ecclesia, ut per oblectamenta aurium {var="animus infirmior ad effectum" Br1 G : "infirmior animus in affectum" (August.)} pietatis assurgat”.**August. Conf. X.xxxiii.50.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De septimo effectu. Capitulum {var=".vii." edC : "7^m" Br1}" Br1 : "Septimus effectus est." G}</heading>\n\
{var="Septimo" Br1 : (om.) G}: Musica tristiciam depellit.**Cf. De inv. et usu I.v, “Quintodecimo”.** Unde Jacobi capitulo {var="quinto" Br1 : "5^to^" G}: “Tristatur aliquis vestrum? {var="Oret equo animo et psallat" Br1 G (Vulg. ante 1592) : "Oret. Aequo animo est? Psallat" (Vulg. ab ed. Clementina, 1592)}.”**Jac. 5:13.** Hinc de Poliphemo Virgilius in {var="tertio" edC : "tercio" Br1 : "2º" G} libro <citation>Eneidos</citation> ait: “solamen{ }que mali de collo fistula pendet”.**Virg. A. III.661; critical editions give this as an incomplete line, ending “mali”, but the completion is attested in the tradition.**\n\
Et quoniam in amore plurimum tristicie accidit, hanc musica quodam innato {var="solamine" Br1 : "solamen" G} depellere solet. Unde idem Virgilius de Orpheo, tristi propter absentiam {var="Euridicis" G : "Erudicis" Br1}, quam flagranter amabat, proprio instrumento se consolante, in {var="quarto" Br1 : "4º" G} libro <citation>Georgicorum</citation> sic inquit:\n\
<verse>Ipse {var="cava" G (Virg.) : "cana" Br1} solans egrum testudine amorem<l/>te, dulcis coniunx, te solo in {var="litore" G : "littore" Br1} secum,<l/>te veniente die, {var="et te cedente" Br1 : "te decedente" (Virg.)} canebat.**Virg. G. IV.464–6.**</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De octavo effectu. Capitulum {var=".viii." edC : "8^m" Br1}" Br1 : "Octavus effectus est." G}</heading>\n\
{var="Octavo" Br1 : (om.) G}: Musica duriciam cordis resolvit.**Cf. De inv. et usu I.v, “Quartodecimo”.** Unde Augustinus in libro nono <citation>Confessionum</citation>: “flevi in {var="hymnis" G : "hympnis" Br1} et canticis tuis, suave sonantis ecclesie tue vocibus commotus acriter”.**August. Conf. IX.vi.14; taken over from Th. Aq. S. theol. II^a^-II^ae^ q. 91 a. 2 co. (cf. more complete quotation in De inv. et usu I.v.37).** Hinc, eo quod populus Judaicus “dure {var="cervicis” erat" Br1 : "erat cervicis" G} (Domino teste Exodi {var="tricesimosecundo" Br1 : ".xxxij.º" G} capitulo),**Ex. 32:9b.** multorum instrumentorum musicorum usus erat ei necessarius, quibus cordium suorum duricia resolveretur, ut patet per Sanctum Thomam {var="in Secunda secunde, questione nonagesimaprima" Br1 : "2^a 2^e qṝe [?quare ?quere] 91^a" G}, articulo {var="secundo" edC : "2º" Br1 G}.**Paraphrase of Th. Aq. S. theol. II^a^-II^ae^ q. 91 a. 2 ad 4.**\n\
Et Orpheum, eo quod musica modulatione {var="duriciam" Br1 : "duritiam" G} rudium et agrestium animorum resolveret, “non feras modo, sed saxa etiam silvas{ }que duxisse posteritatis {var="memorie" Br1 : "memoria" G} traditum est”: hec Quintilianus in libro primo <citation>{var="Institutionum" G : "Institucionum" Br1} oratoriarum</citation>.**Quint. Inst. I.x.9, preceded by “quia rudes quoque atque agrestes animos admiratione mulceret”.** {var="Simile" Br1 : "Salē [Salem]**Tinctoris’s MS apparently had the abbreviation in Br1: “siłe”.**" G} cuius {var="Amphion" (ed.) : "Amphyon" Br1 G} fecisse dicitur, de quo Oratius in suis <citation>Odis</citation>: “movit {var="Amphion" (ed.) : "Amphyon" Br1 G} lapides canendo”,**Hor. Od. III.xi.2.** et {var="Statius" G : "Stacius" Br1} libro primo <citation>{var="Thebaidos" Br1 : "Theobaidos" G}</citation>:\n\
<verse>                                                quo carmine muris<l/>iusserit {var="Amphion" (ed.) : "Amphyon" Br1 G} Tyrios accedere montes.**Stat. Theb. I.9–10.**</verse>\n\
{var="Immo" Br1 : "Ymmo" G} poete, ad ostendendum maiorem efficatiam musice circa duriciam cordis resolvendam, fingunt ipsum Orpheum et manes et iudices et monstra inferorum suo cantu movisse, de quo Virgilius in {var="quarto" Br1 : "4^to^" G} <citation>Georgicorum</citation> hec dicit:\n\
<verse>{var="Tenarias" Br1 : "Trenarias" G} etiam fauces, alta {var="ostia" G : "hostia" Br1} Ditis,<l/>et caligantem nigra formidine lucum<l/>ingressus manes{ }que adiit regem{ }que tremendum<l/>nescia{ }que humanis precibus mansuescere corda.<l/>{var="Ac" Br1 G : "At" (Virg.)} cantu commote Herebi de sedibus {var="imis" (edC) : "ymis" Br1 G}<l/>umbre ibant tenues simulachra{ }que luce {var="carentum" G : "carentiū [carentium]" Br1}.</verse>\n\
Et paulo post sequitur:\n\
<verse>Quin ipse stupuere domus atque intima Leti<l/>Tartara ceruleos{ }que {var="amplexe" Br1 G : "implexae" (Virg.)} crinibus angues<l/>Eumenides tenuit{ }que inhians tria Cerberus ora<l/>atque {var="Ixionii" (edC) : "Yxionii" Br1 : "Yptonii" G} vento {var="rota" Br1 : (om.) G} constitit orbis.**Virg. G. IV.467–72, 481–4.**</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De nono effectu. Capitulum {var=".ix." edC : "9^m" Br1}" Br1 : "Nonus effectus est." G}</heading>\n\
{var="Nono" Br1 : (om.) G}: Musica diabolum fugat.**Cf. De inv. et usu I.v, “Decimooctavo”.** Unde Primi Regum {var="sextodecimo capitulo" Br1 : "caº 16º" G}: “David tollebat {var="citharam" G : "cytharam" Br1}, et {var="psallebat" Br1 G : "percutiebat" (Vulg.)} manu sua, {var="refocillabatur{ }que" Br1 G : "et refocillabatur" (Vulg.)} Saul, et levius habebat: {var="recedebat enim" Br1 : "recedebatque" G} ab eo spiritus malus”.**1 Sam. 16:23b.** Super {var="quo" Br1 : "quod" G} rhetor**At this point Br1 is mutilated: the next leaf was torn, leaving a stub in the lower back, from which a few fragments of chaps. xii and xvi can be retrieved; the following, last leaf has left no trace.** quidem hos versus edidit:\n\
<verse>{var="Rex" G : "Sic" (Perseus)} David in Saule sedavit demonis iram,<l/>Ostendens cithare virtutem carmine miram.</verse>**Perseus S. musice ii.298–9 (p. 147 Page; iii.196 Gerbert).**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De decimo effectu. Capitulum .x." edS : "Decimus effectus est." G}</heading>\n\
{var="Decimo" edZ : (om.) G}: Musica extasim causat.**Cf. De inv. et usu I.v, “Tertiodecimo”.** Unde postquam David in Psalmo sexagesimoseptimo cecinit, “Prevenerunt principes coniuncti psallentibus, in medio iuvencularum tympanistriarum”, {var=(ins.) "Et" G} paulo post subdidit, “Ibi Beniamin adolescentulus, in mentis excessu”.**Ps. 67:26, 28a.** Pro {var="quo" edZ : (om.) G} facit illud Philosophus in {var="octavo" edZ : "8º" G} <citation>Politicorum</citation>: “{var="melodie {var="Olympi" edC : "Olimpi" G}" G : "per melodias Olympi: hae enim confesse" (Aristot.)} faciunt animas raptas”.**Aristot. Pol., trans. G. de Moerbeke, 1340a9–11 (VIII.v.5). Olympus was a 7th-c.-BC aulete and composer of Phyrgian origin; since Tinctoris cast the next quotation as “confirmation”, he evidently expected his readers to know this.** Ad cuius confirmationem referente Quintiliano in primo <citation>Institutionum oratorium</citation>, “ponitur tibicen, qui sacrificanti {var="Phrygium" edS : "frigium" G} cecinerat, acto illo in insaniam et per precipicia delato accusari, quod causa mortis {var="extiterit" (Quint.) : "extiterunt" G}”.**Quint. Inst. I.x.33.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De undecimo effectu. Capitulum .xi." edS : "Undecimus effectus est." G}</heading>\n\
{var="Undecimo" edZ : (om.) G}: Musica terrenam mentem elevat.**Cf. De inv. et usu I.v, “Octavo”.** Unde {var="Bernardus" edS : "Barnardus" G} super Cantica: “Oculos cordis attollit iubilus laudis.”**Quotation not found anywhere in PL. Cf. Prosp. Aq. Exp. in Ps. 120:1–2: “Ingressus viam virtutum, in qua sunt gradus ascensionum ad montes, id est, ad sublimes quosque sanctorum, <italic>oculos cordis attollit</italic> et per ipsos Dei poscit auxilium qui fecit coelum et terram.” (emphasis added; PL li.365a–b)** Armonie quidem dulcedine {var="movetur" edZ : "movet" G} mens ad contemplationem gaudiorum supernorum, que {var="summa" edZ : "seī-ma [?septima]" G} pars est vite melioris, et hinc deficit a cogitatione terrenorum, que ad actionem vite pertinens sollicitudinem ac turbationem inducit.**The thought here greatly resembles August. Conf. X.xxxiii.49, but not the language.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De duodecimo effectu. Capitulum .xii." edS : "De du-" Br1 : "Duodecimus effectus est." G}</heading>\n\
{var="Duodecimo" edZ : "Duodeci-" Br1 : (om.) G}: Musica voluntatem malam revocat.**Cf. De inv. et usu I.v, “Vigesimo”.** Nam ut Cicero dicit in libro <citation>De {var="consiliis" edC : "conciliis" G}</citation>**Cic. De cons. (lost), quoted in Boe. Mus. I.i (p. 185.9–17 Friedlein).** refert{ }que Quintilianus in libro primo <citation>{var="Institutionum" G : "Institucionum" Br1} oratoriarum</citation>: “concitatos ad vim pudice {var="domui" (Quint.) : "domi" G : "do-" Br1} {var="inferendam" G : "adferendam" (Quint.)} iuvenes, {var="mutare iussa" G : "iussa mutare" (Quint.)} in spondeum modos tibicina, {var="{var="Pythagoras" (edC) : "Pictagoras" G} composuit" G : "Nam et Pythagoran accepimus concitatos … tibicina, composuisse" (Quint.)}”.**Quint. Inst. I.x.32.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De tertiodecimo effectu. Capitulum .xiii." edS : "Tertiusdecimus effectus" G}</heading>\n\
{var="Tertiodecimo" edZ : (om.) G}: Musica homines letificat.**Cf. De inv. et usu I.v, “Nono”.** Nanque prout refert Aristoteles in {var="octavo" edC : "8º" G} <citation>Politicorum</citation>, “{var="Museus ait" G : "ait enim et Musaeus" (Aristot.)} esse hominibus delectabilissimum cantare; propter quod in conventus et deductiones rationabiliter assumunt {var="ipsam" (Aristot.) : "ipsum" G} tanquam potentem letificare”.**Aristot. Pol., trans. G. de Moerbeke, 1339b21–4 (VIII.v.2); the latter part of the quotation is Aristotle’s own comment on Musaeus’ statement.**\n\
{var="Et" edC : "C" G} letificat alios quidem plus, et alios minus. Nanque quanto plus in hac arte perfectus est, tanto plus ab ea delectatur, eo quod naturam ipsius et interius et exterius apprehendat: interius quidem virtute intellectiva, qua intelligit debitam compositionem ac pronuntiationem, et exterius potentia auditiva, qua percipit concordantiarum dulcedinem. Tales autem sunt solum qui de ipsa musica vere iudicare delectari{ }que possunt; propter quod Philosophus in {var="octavo" edZ : "8º" G} <citation>Politicorum</citation> consulit iuvenibus operam dare musice, ut non tantum sono per se sive per alium delectentur, sed senes etiam effecti, dimissis operibus, de ea recte possint iudicare.**Summary of Aristot. Pol., trans. G. de Moerbeke, 1340b20–39 (VIII.vi.1–2).**\n\
Musica vero minus illos letificat qui nihil ex ea penitus quam sonum percipiunt. Extrinseco etenim sensu tantummodo delectantur. Afficiuntur adeo tamen tali sono quod, iuxta Juvenalem, “currentes ad vocem iocundam”, eos qui voce delectabili (sicut opinantur) canunt, licet rudissime pronuntient, tanquam optimos musicos predicant et extollunt.**Juv. III.vii.82–7: “Curritur ad vocem iucundam et carmen amicae / Thebaidos, laetam cum fecit Statius urbem / promisitque diem: tanta dulcedine captos / adficit ille animos tantaque libidine volgi / auditur; sed cum fregit subsellia versu, / esurit, intactam Paridi nisi vendit Agauen.”** Neque miror {var="quom" (ed.) : "cum" G} Virgilium cecinisse <citation>Bucolicorum</citation> egloga {var="secunda" edC : "2ª" G} legerim: “Trahit sua {var="quenque" (ed.) : "quemque" G} voluptas”.**Virg. Ecl. ii.65.**\n\
Perfectio igitur delectationis musice consistit in eius perfecta cognitione. Unde {var="Aristoteles" (edC) : "Aristotiles" G} in {var="octavo" edC : "8º" G} <citation>Politicorum</citation> ponit ad propositum quod “{var=(ins.) "neque enim" (Aristot.)}imperfecto {var=(ins.) "supple in apprehensione ipsius artis musice**An analogous explanation in G beginning “supple” (=i.e.) is certainly an interpolation in Prop. mus. III.ii.21; the expression does not otherwise occur in Tinctoris’s writings.**" G} {var="non" G : (om.) (Virg.)} convenit finis”,**Aristot. Pol., trans. G. de Moerbeke, 1339a31 (VIII.iv.4).** idest perfectio eius delectationis.\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De quartodecimo effectu. Capitulum .xiv." edS : "Quartus decimus effectus" G}</heading>\n\
{var="Quartodecimo" edZ : (om.) G}: Musica egrotos sanat.**Cf. De inv. et usu I.v, “Tertio et vigesimo”.** Unde refert Isidorus {var="in" edZ : (om.) G} {var="quarto" edC : "4º" G} libro <citation>Ethimologiarum</citation>, quod “Asclepiades {var=(ins.) "quoque" (Isid.)} medicus {var="quendam freneticum" G : "phreneticum quendam" (Isid.)} {var="arte modulationis" G : "per symphoniam" (Isid.)} pristine {var="restituit sanitati" G : "sanitati restituit" (Isid.)}.”**Isid. Etym. IV.xiii.3.** Hinc dicit idem auctor eminentissimus musicam fore medico necessariam.**Paraphrase of Isid. Etym. IV.xiii.3: “Porro Musica incognita illi non erit, nam multa sunt quae in aegris hominibus per hanc disciplinam facta leguntur”.** Quod satis probabile videtur ex dictis Avicenne et Galieni, quorum primus ait: “Debes autem scire quod in pulsu reperitur natura musice”,**Avic. Canon, trans. G. Cremonensis (<italic>not</italic> Cant.), I. fen 2 doctr. 3 summa 1 c. 1 (ed. Juntas 1555, 47e14); cf. Gal. De diff. puls. I.viii (viii.516–17 Kühn).** et alter: “{var="Quom" (ed.) : "cum" G} natura proportionum musicalium mihi nota fuit, tunc ianue pulsus mihi aperte fuerunt.”**Quotation not found. Cf. Avic. Canon, trans. G. Cremonensis, I. fen 2 doctr. 3 summa 1 c. 1 (ed. Juntas 1555, 47a11–13, 47f7–8): “Galenus quoque dixit, ‘longo tempore non fui solicitus ex depressione, postea vero non quievi tangendo, donec ex eo aliquid percepi, & postea illud complevi: <italic>nam postea portae pulsus mihi apertae fuerunt</italic>.’ [emphasis added; cf. Gal. De dig. puls. I.iii (viii.787–9 Kühn), i (viii.770–72 Kühn)] … Galenus autem videtur, quod id, quod potest sentiri ex proportionalitatibus ponderis, est secundum unam proportionem musicarum [cf. Gal. De diff. puls. I.viii (viii.516–17 Kühn, i.76ra 1490): ‘Quoniam autem primum tempus non ad naturam ipsam sed ad sensum intelligere oportet palam est. Ita enim habet et apud musicos.’]”.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De quintodecimo effectu. Capitulum .xv." edS : "Quintus decimus effectus" G}</heading>\n\
{var="Quintodecimo" edZ : (om.) G}: Musica labores temperat.**Cf. De inv. et usu I.v, “Secundo et vigesimo”.** Nam ut habet Quintilianus in primo libro <citation>Institutionum oratoriarum</citation>, “natura ipsa videtur nobis {var="musicam" G : "eam" (Quint., transp.)} ad tolerandos facilius labores dedisse, siquidem {var="remiges" G : "et remigem" (Quint.)} cantus {var="hortantur" G : "hortatur" (Quint.)}”.**Quint. Inst. I.x.16. Cf. Isid. Etym. III.xvii.2 (cited in chap. xvi below): “Siquidem et remiges cantus hortatur, ad tolerandos quoque labores musica animum mulcet”.** Pro quo facit illud Virgilii <citation>Bucolicorum</citation> egloga nona: “cantantes licet usque (minus via ledit) eamus”,**Virg. Ecl. ix.64.** et in primo libro <citation>Georgicorum</citation>:\n\
<verse>interea longum cantu solata laborem<l/>arguto coniunx percurrit pectine {var="telas" (Virg.) : "tollas" G}.**Virg. G. I.293–4.**</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De sextodecimo effectu. Capitulum .xvi." edS : "Sextus decimus effectus." G}</heading>\n\
{var="Sextodecimo" edZ : (om.) G}: Musica animos ad prelium incitat.**Not in De inv. et usu I.v.** Hinc habetur de Misseno, qui in obsidione Troiana cum Hectore prestantissime lituo prelium accendebat,**Misenus is not in Homer; cf. Prop. III.xviii.3; Stat. Silv. III.i.150–51, IV.vii.17–20, V.iii.167–8.** quod {var="quom" (ed.) : "cum" G} ipse Missenus, Hectore mortuo sequutus {var="Eneam" edC : "encam" G} per equora, facere niteretur, a Tritone, Neptuni {var="tubicine" edC : "eubicine" G}, per invidiam fuit submersus.**Cf. Virg. A. VI.156–235.** De quo Virgilius {var="in" (ed.) : (om.) G} <citation>Eneidos</citation> libro sexto sic ait:\n\
<verse>              Atque illi {var=(ins.) "perimunt" G} {var="Missenum" (Virg.) : "Messenum" G} in littore sicco,<l/>ut venere, vident indigna morte peremptum,<l/>Missenum Eoliden, quo non prestantior alter<l/>{var="ere ciere" (Virg.) : "erecire" G} viros Martem{ }que accendere cantu.<l/>(et cetera que ibi sequuntur)**Virg. A. VI.162–5.**</verse>\n\
Hinc {var="Timotheus" (edS) : "Thimotheus" G}, {var="tibicen" edZ : "tubicen" G} Alexandri Magni, illum ab epulis in bellum sepenumero provocasse legitur.**Cf. D. Chrys., trans. G. Tiphernas, i.1; Bas. Caes. De leg. gent. lib., trans. L. Bruni, viii.8. See also De inv. et usu III.ix.37.** Cui concordat Quintilianus in libro {var="primo" edC : ".i.º" G} <citation>Institutionum oratoriarum</citation>: “Duces maximos et fidibus et tibiis {var="concinisse" G : "con-" Br1 : "cecinisse" (Quint.)} traditum {var="est" G : (om.) (Quint.)} et exercitus Lacedemoniorum musicis accensos modis.”**Quint. Inst. I.x.14.** Tales autem melodie sunt ire provocative, ut vult Philosophus in octavo <citation>Politicorum</citation>;**Aristot. Pol., trans. G. de Moerbeke, 1340a19 (VIII.v.6).** que quanto sunt vehementiores, tanto certantium animos efficiunt fortiores (hec {var="Isidorus" (edS) : "Ysidorus" G} {var="in" (ed.) : (om.) G} <citation>Ethimologiarum</citation> libro {var="tertio" edC : "tercio" G}),**Paraphrase of Isid. Etym. III.xvii.2: “In proeliis quoque tubae concentus pugnantes accendit, et quanto vehementior fuerit clangor, tanto fit ad certamen animus fortior.”** quo finaliter gloriam victorie consequuntur. Unde Quintilianus in libro primo <citation>Institutionum oratoriarum</citation>: “Quid autem aliud in nostris legionibus cornua ac tube faciunt? quorum concentus quanto est vehementior, {var="tantum" Br1 : "tanto" G} Romana in bellis gloria ceteris prestat.”**Quint. Inst. I.x.14.**\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De decimoseptimo effectu. Capitulum .xvii." edS : "Septimus decimus effectus." G}</heading>\n\
{var="Decimoseptimo" (ed.) : (om.) G}: Musica amorem allicit.**Cf. De inv. et usu I.v, “Decimo”.** Unde Ovidius puellis amorem virorum allicere cupientibus precipit ut cantare discant; enimvero in {var="tertio" edC : "3º" G} libro <citation>De arte amandi</citation> sic inquit:\n\
<verse>Res est blanda canor: discant cantare puelle:<l/>    pro facie multis vox sua lena fuit.**Ov. Ars III.315–16.**</verse>\n\
Hinc est quod {var="quom" (ed.) : "cum" G} Orpheus {var="lyram" edS : "liram" G} dulcissime pulsaret, multas mulieres eius amorem incensas a poetis traditum est. De quo Ovidius {var="in" (ed.) : (om.) G} <citation>Metamorphoseos</citation> libro decimo:\n\
<verse>                              Multas tamen ardor habebat<l/>iungere se vati, multe doluere repulse.</verse>\n\
Immo melodia cantus ipsius Orphei tante {var="certe" edC : "certa" G} {var="ad" edZ : (om.) G} amorem alliciendum erat efficacie, ut et impuberes ad amandum cogeret, unde ibidem sequitur:\n\
<verse>Ille etiam Thracum populis fuit auctor amorem<l/>in {var="teneres" G : "teneros" (Ov.)} transferre mares citra{ }que iuventam<l/>etatis breve ver et primos carpere flores.**Ov. Met. X.81–2, 83–5.**</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De decimooctavo effectu. Capitulum .xviii." (ed.) : "Octavus decimus effectus." G}</heading>\n\
{var="Decimooctavo" (ed.) : (om.) G}: Musica iocunditatem convivii augmentat.**Cf. De inv. et usu I.v, “Undecimo”.** Unde Ecclesiastici {var=(ins.) "in" edZ} capitulo {var="tricesimosecundo" (ed.) : "trigesimosecundo" G}: “{var="Gemme" G : "Gemmula" (Vulg.)} carbunculi in ornamento auri, et comparatio musicorum in convivio vini.”**Eccli. 32:7.** Glosa: “{var="Carbunculum" G : "Hunc" (Glossa)} comparat auro, et musicum melos convivio; sicut enim carbunculus duplicat splendorem auri, ita melodia iocunditatem convivii.”**Glossa ord. ad loc. (PL 113: 1216b is inaccurate), derived from Rab. Maur. In Eccli. VII.ix (PL 109: 994c–d).**\n\
Hinc tradunt poete deorum epulis musicam esse acceptam. Unde Oratius in suis <citation>Odis</citation> scribit:\n\
<verse>O decus Phebi et dapibus {var="supremis" G : "supremi" (Hor.)}<l/>grata testudo Jovis, o laborum<l/>dulce lenimen, mihi cunque salve<l/>    rite vocanti!**Hor. Od. I.xxxii.13–16.**</verse>\n\
Verum ab antiquo claros homines epulantes assumere musicam non insolitum est. Unde Virgilius, recitans ea que in opiparo convivio ab Elissa {var="Enee cum" edZ : "Eneeque" G} suis {var="sociis" edC : "sotiis" G} preparato gesta fuerunt, adducit {var="Iopam" (edS) : "Yopam" G}, citharedum peritissimum, quo {var="iocundius" edZ : "iucundius" G} esset, citharam increpuisse; de quo {var="in" (ed.) : (om.) G} <citation>Eneidos</citation> libro primo: “Cithara crinitus {var="Iopas" (edS) : "Yopas" G} / personat aurata” (et cetera).**Virg. A. I.740–41.** “Veterum quoque Romanorum epulis fides {var="et" G : "ac" (Quint.)} tibias adhibere moris fuit”; hec Quintilianus in libro primo <citation>Institutionum oratoriarum</citation>.**Quint. Inst. I.x.20.** Et {var="Isaie" (edS) : "Ysaie" G} {var="quinto" edS : "5º" G} capitulo legitur, “{var="Cithara" (ed.) : "Cythara" G}, et {var="lyra" edS : "lira" G}, et tympanum, et tibia, et vinum in conviviis vestris”.**Is. 5:12a. This is part of a series of comminations; the second half of the verse is “et opus Domini non respicitis, nec opera manuum eius consideratis”.**\n\
{var="Hanc" edC : "Han" G} quoque consuetudinem hac tempestate plurimum vigere videmus: magnatibus splendide ac solenniter epulantibus, quod genus musicorum {var="non" edZ : (om.) G} adesse sentimus? Illic cantores, illic tibicines, illic tympaniste, illic organiste, illic citharedi, illic fistule, illic tube, adeo melodiose concinentes ut vera quedam ymago supernorum gaudiorum esse videatur.\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De decimonono effectu. Capitulum .xix." (ed.) : "Nonus decimus effectus est." G}</heading>\n\
{var="Decimonono" (ed.) : (om.) G}: Musica peritos in ea glorificat.**Cf. De inv. et usu I.v, “Sexto et vigesimo”.** Unde Ecclesiastici {var="capitulo" (ed.) : (om.) G} quadragesimoquarto: “Homines {var=(ins.) "[vv. 3b–4]" (Vulg.)} in {var="peritia" (Vulg.) : "pueritia" G} sua requirentes modos musicos, {var=(ins.) "[vv. 5b–6]" (Vulg.)} in generationibus gentis sue gloria adepti sunt, et in diebus suis habentur in laudibus.”**Eccli. 44:3a, 5a, 7.**\n\
Et quoniam olim in Grecia summa musici afficiebantur gloria propter “summam eruditionem” quam ipsi “Greci sitam censebant in nervorum vocum{ }que cantantibus”, non modo prestantissimi viri, philosophi operam illi {var="impenderunt" edC : "inpenderunt" G}, ut Socrates, {var="Pythagoras" edC : "Pictagoras" G}, Plato, {var="Aristoteles" edC : "Aristotiles" G}, sed et bellicosissimi principes, ut {var="Epaminundas" edC : "Examinundas" G} et Achilles. “Themistocles{ }{var="que" (Cic.) : " qui" G}, {var=(ins.) "aliquot ante annos" (Cic.)} {var="quom" (ed.) : "cum" G} in epulis recusaret {var="lyram" edS : "liram" G}, {var="habitus est" G : "est habitus" (Cic.)} indoctior”. {var="Immo vero" edZ : "Ymmo ut" G} et cum hoc Cicero ponit in prologo <citation>Questionum Tusculanarum</citation>: “discebant{var=(ins.) "que" (Cic.)} id omnes, nec qui nesciebat satis excultus doctrina putabatur”.**Cic. Tusc. I.iv.3–4.**\n\
Nostro autem tempore experti sumus {var="quanta" edZ : "quanti" G} plerique musici gloria sunt affecti. Quis enim {var="Joannem" (edC) : "Johannem" G} Dunstaple, Guillermum Dufay, Egidium Binchois, {var="Joannem" (edC) : "Johannem" G} Okeghem, Anthonium {var="Busnoys" (ed.) : "Busnois" G}, {var="Joannem" (edC) : "Johannem" G} Regis, Firminum Caron {var=(ins.) "Jacobum Carlerii, Robertum Morton, Jacobum Obrechts" G} non novit?**G’s inclusion at the end of this list of the names of Jacques Carlier (almost unknown, with no music surviving) and Jacob Hobrecht (evidently still a choirboy when Tinctoris wrote) on either side of Robert Morton are almost certainly interpolations, possibly as late as its copying in 1503. Although we can be certain Tinctoris knew Morton’s music (he made two arrangements of Morton’s <italic>Le souvenir de vous me tue</italic>, and other chansons of Morton’s are in the Mellon chansonnier (US-NHub 91), dedicated to Beatrice d’Aragona and with whose preparation Tinctoris seems to have been involved), his name too is omitted from the parallel passage in Prop. mus. Prol.10–11, written about the same time.** Quis eos summis laudibus non prosequitur, quorum {var="compositiones" edC : "conpositiones" G}, per universum orbem divulgate, Dei templa, regum palacia, privatorum domos summa dulcedine replent? Taceo plurimos musicos eximiis opibus dignitatibus{ }que donatos, quoniam {var="etsi" edS : "et si" G} honores ex {var="his" (ed.) : "hiis" G} adepti sunt, fame immortali quam primi compositores sibi extenderunt, minime sunt conferendi. Illud enim fortune, istud autem virtutis opus est; unde Virgilius {var="in" (ed.) : (om.) G} <citation>Eneidos</citation> libro {var="decimo" edC : "xº" G}:\n\
<verse>Stat sua cuique dies, breve et irreparabile tempus<l/>omnibus est vite: sed famam extendere factis,<l/>hoc virtutis opus.**Virg. A. X.467–9.**</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>{var="De vicesimo effectu. Capitulum .xx." edS : "Vicesimus effectus musice" G}</heading>\n\
{var="Vicesimo" edZ : (om.) G}: Musica animas beatificat.**Cf. De inv. et usu I.v, “Septimo et vigesimo”.** Nulli nanque dubium est homines ad compunctionem audiendo cantum induci; propter hoc enim Ecclesia Dei laudes cantari instituit, ut patet per capitulum “Cleros” {var="vicesimeprime" (ed.) : "21." G} distinctionis**Paraphrase of Decr. Grat. pars I, XXI.i.15–16 (i.69 Friedberg): “Lectores a legendo, psalmistae a psalmis canendis uocati; … isti canunt, ut excitent ad compunctionem animos audientium”.** et per Doctorem Sanctum {var="in Secunda secunde, questione nonagesimaprima, articulo secundo" edS : "2^a 2^e q. xci^a ar. 2^o" G}.**Th. Aq. S. theol. II^a^-II^ae^ q. 91 a. 2 co., ad 5.** Unde, {var="quom" (ed.) : "cum" G} per {var="compunctionem" edC : "conpunctionem" G} anime salutem attingant, sequitur musicam huiusmodi salutis esse causam. Que quidem salus summa beatitudo est, quam {var="non modo" edC : "nōmodo [nommodo]" G}, ut prediximus, qui musicam audiunt, sed et qui sciunt assequitur. Unde propheta {var="in" (ed.) : (om.) G} Psalmo octogesimooctavo: “Beatus populus qui scit iubilationem.”**Ps. 88:16a.**\n\
</chapter>\n\
<conclusion>\n\
<heading>{var="Operis" (ed.) : "Sequitur" G} conclusio.</heading>\n\
Hos igitur effectus si quis advertat, nunquam ei pigebit ingenium suum huic parti discipline applicuisse; {var="immo" edS : "ymmo" G} in dies affectu flagrantissimo melodie studebit, qua reges, qua ceteros principes, qua{ }que liberos homines usos fuisse et uti gloriosum et commendabile est. Hec enim est, que a {var="Licurgo" edZ : "Ligurgo" G}, Platone, Quintiliano approbatur precipitur{ }que,**Quint. Inst. I.x.15.** quorum precepta qui sequitur et ars ille et ille arti decori in sempiternum erit.\n\
</conclusion>\n\
<explicit>{var="Finit <citation>Complexus effectuum musices</citation>." (ed.) : "Et hec de commendatione nobilis artis musices." G}\n\
{var=(ins.) "Hec Magister Johannes Tinctoris in legibus licenciatus serenissimi principis Ferdinandi, Sicilie, Jherusalem et Ungarie regis capellanus." G}</explicit>\n\
</treatise>';
texts.complexus.translation = {};
texts.complexus.translation.english = 'Complexus effectuum musices\n\
Translator: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 22 March 2024\n\
<treatise>\n\
<title>An encompassing of the effects of music: published by master Johannes Tinctoris, licentiate in law and chaplain of the king of Sicily</title>\n\
<prologue>\n\
<heading>Prologue</heading>\n\
To the most illustrious lady Beatrice d’Aragona, most virtuous daughter of the king of Sicily, Jerusalem, and Hungary, Johannes Tinctoris, least among those professing the law and the mathematical arts, pledges undying service. It occurs to me, most blessed Beatrice, knowing with what ardent and what strenuous application you devote effort to the noble art of music, to expound succinctly to your Highness some of its remarkable effects. You should be stimulated by them (though I judge your mind to be very steadfast, like his from whom it drew its heavenly origin) never to desist from such a distinguished effort. I have undertaken this, too, moved no less by love of you than of the art. Certainly, as it is as welcome to me as can be that music, to which I have dedicated myself from a tender age, will be the study of such an illustrious, such an intelligent, and such a beautiful royal princess, so also I wish your mind to be always thoroughly purified from every sorrow by the help of this art that Plato declares to be the “most powerful” science of all, Quintilian the “most beautiful”, and Augustine “divine”. And you must not suppose that I intend all the effects of this “liberal and honorable” music (so Aristotle calls it) to be encompassed in this little work, but only twenty, which are:\n\
<table>\n\
Delighting God;\n\
    Adorning the praises of God;\n\
Increasing the joys of the blessed;\n\
    Making the Church Militant like the Triumphant;\n\
Preparing for acceptance of the divine blessing;\n\
    Stimulating minds to devotion;\n\
Dispelling sadness;\n\
    Softening hardness of heart;\n\
Putting the devil to flight;\n\
    Causing ecstasy;\n\
Lifting up the earthly mind;\n\
    Restraining ill will;\n\
Gladdening people;\n\
    Healing the sick;\n\
Lightening labours;\n\
    Rousing the spirits to battle;\n\
Enticing love;\n\
    Increasing the enjoyment of a banquet;\n\
Glorifying those skilled in it;\n\
    Blessing souls.\n\
</table>\n\
I have decided, too, to attest these admirable and (if I may say so) divine effects now by arguments, now by sacred authorities, now by the sayings of philosophers, historians, and poets (which are customarily sought “to establish belief”, according to Cicero), and I have set about to discuss them in due order of each so that they may be more plainly clear. And although you may recognize the abilities of a singer as unequal to this publication because it is difficult, concerning now theology, now philosophy, now poetry, surely you will hardly accuse me of the vice of presumption if you are not unaware that stretching for the difficult is appropriate to virtue.\n\
</prologue>\n\
<chapter>\n\
<heading>On the first effect of music. Chapter 1 [i].</heading>\n\
First: Music delights God. For it is a property of any artist to take delight in their art, especially when it is perfect. Whence, since God, who “does not create a work of imperfection” (as is held in the <citation>Decretals of Gregory IX</citation> in the chapter “Maiores”, “On baptism and its effect”), of old wrought this most perfect art, it must be maintained that by it above all he takes delight. Hence from his most beloved bride (whom the faithful believe to be the Church) he wishes to hear the sweetness of her voice, which music alone can accomplish. Indeed, through Solomon in the Song of songs, chapter 2, he addresses her thus: “let thy voice sound sweet in my ears”, and there follows, “for thy voice is sweet”, as if he would say, “Because thy voice is sweet (that is, melodious), I wish that it should sound in my ears.” And God would not wish to hear the sweetness of a voice if it did not delight him in any way.\n\
</chapter>\n\
<chapter>\n\
<heading>On the second effect. Chapter 2 [ii].</heading>\n\
Second: Music adorns the praises of God. Hence in the Church Triumphant, those devoting themselves to the ceaseless praises of God are said to sing them, so that they may be adorned the more. Whence John reports in Revelation, chapter 14, that a voice of people singing “as it were a new canticle before the throne” of God was “as the voice of harpers, harping on their harps”.\n\
Hence Virgil imagines those who were in the Elysian Fields as singing praises of Apollo, the god of wisdom. For in the <citation>Aeneid</citation>, book 6, he says of Aeneas, who had arrived in that place with the sibyl:\n\
<verse>Look, he observes others to right and left, eating<l/>on the grass and joyfully singing a paean in chorus.</verse>\n\
Likewise, priests under Evander used to sing praises in the Arcadian manner to the god Hercules, on which Virgil, again, says in book 8:\n\
<verse>Then the Salii are present around the burning altar<l/>to sing, heads wreathed with poplar branches,<l/>this chorus of youths, that of elders; they offer praises<l/>of Hercules and his deeds with song: (and the rest)</verse>\n\
And Numa Pompilius, the most pious founder of the Roman rites, wanted the Salii to adorn the praises of the gods with musical verses. Whence Quintilian in the <citation>Institutes of oratory</citation>, book 1: “The verses of the Salii also have their tune.”\n\
But these pertain to false religion. King David, however, cultivator of true religion, desiring to adorn the praises of God, instituted singers who descanted them before the ark of the covenant, on which in Ecclesiastes, chapter 47: “he set singers before the altar, and by their voices he made sweet melody”. Hence, seeking for the praises of God to be adorned by all different musical instruments, after he has said in the 146th Psalm, “to our God be joyful and comely praise”, he adds in the last one:\n\
<verse>Praise him with sound of trumpet;<l/>praise him with psaltery and harp.<l/>Praise him with timbrel and choir;<l/>praise him with strings and organs.<l/>Praise him on high sounding cymbals;<l/>praise him on cymbals of joy.<l/>Let every spirit praise the Lord!</verse>\n\
In the manner of this royal institution, Ambrose first ordained the praises of God in the Church Militant to be adorned with music. For which reason it has come about that at this time are found the most excellent singers free to apply themselves most carefully to the praises of God; the office of these singers, indeed, is the more excellent to the extent that God, whom they devoutly serve by singing, excels everything else.\n\
</chapter>\n\
<chapter>\n\
<heading>On the third effect. Chapter 3 [iii].</heading>\n\
Third: Music increases the joys of the blessed. For we believe blessedness to be a state completed by the accumulation of all good things; if the blessed have achieved it, the most delightful things that are good cannot be lacking to them. Whence, since (as the Philosopher [Aristotle] says in the <citation>Politics</citation>, book 8) music is “one of the most delightful things”, we infer by reason that the sweetness of musical concords increases their joys. Hence, since musical instruments signify the happiness of blessed spirits (as is clear through Ovid in the <citation>Metamorphoses</citation>, book 4, saying: “both lyres and pipes and song sound, the gladsome signs of merry minds”), painters, when they want to represent the joys of the blessed, depict angels sounding various musical instruments. The Church would not permit this unless it believed music to increase the joys of the blessed.\n\
Nor is it beside the point that Virgil imagined music being present among the joys of the Elysian Fields, which he calls “pleasant lawns, joyful places, fortunate groves, and blessed abodes”. Whence in the <citation>Aeneid</citation>, book 6, of those who were rejoicing together in those fields, he says this:\n\
<verse>Some stamp dances with their feet and sing songs.<l/>And also the Thracian priest [Orpheus] with his long robe<l/>accompanies with the measures of seven distinct pitches;<l/>now he strikes them with his fingers, now with an ivory plectrum.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the fourth effect. Chapter 4 [iv].</heading>\n\
Fourth: Music makes the Church Militant like the Triumphant. Whence Bernard on the Song of songs: “nothing on earth so displays the state of the heavenly dwelling-place as the joyfulness of those praising God”. Augustine writes in the same sense, saying in <citation>The city of God</citation>, book 17, chapter 14: “For the rational and measured harmony of diverse sounds in concordant variety indicates the compact unity of the well-ordered city of God.”\n\
</chapter>\n\
<chapter>\n\
<heading>On the fifth effect. Chapter 5 [v].</heading>\n\
Fifth: Music prepares for acceptance of the divine blessing. Whence in 4 Kings, chapter 3: “while the minstrel played, the hand of the Lord came upon Elisha”.\n\
</chapter>\n\
<chapter>\n\
<heading>On the sixth effect. Chapter 6 [vi].</heading>\n\
Sixth: Music stimulates minds to devotion. Whence Augustine in the <citation>Confessions</citation>, book 10: “I am inclined to approve of the custom of singing in church, so that through the delights of the ears a weaker mind may rise up to the accomplishment of devotion”.\n\
</chapter>\n\
<chapter>\n\
<heading>On the seventh effect. Chapter 7 [vii].</heading>\n\
Seventh: Music dispels sadness. Whence in James, chapter 5: “Is one of you sad? Let him pray with a patient mind and sing.” Hence Virgil says of Polyphemus in the <citation>Aeneid</citation>, book 3: “and a recorder, the solace of his woes, hangs from his neck”.\n\
And since sadness very often happens in love, music, with an inherent solace, is accustomed to dispel it. Whence Virgil, again, says about Orpheus, sad on account of the absence of Euridice, whom he ardently loved, consoling himself with his own instrument, in the <citation>Georgics</citation>, book 4:\n\
<verse>He, consoling his love-sickness with the hollow lyre,<l/>sang of thee, his sweet wife, thee by himself on the lonely shore,<l/>thee in the dawning day, and thee in the waning.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the eighth effect. Chapter 8 [viii].</heading>\n\
Eighth: Music softens hardness of heart. Whence Augustine in the <citation>Confessions</citation>, book 9: “I wept in thy hymns and canticles, bitterly moved by the sweetly sounding voices of thy Church”. Hence, since the Jewish people was “stiff necked” (witness the Lord in Exodus, chapter 32), the use of many musical instruments was necessary for them, by which the hardness of their hearts was softened, as is clear through St Thomas [Aquinas] in the Second part of the second part [of the <citation>Summa theologiae</citation>], question 91, article 2.\n\
And Orpheus, since he softened the hardness of rude and rustic minds by musical melody, “was said in the memory of posterity to have led not only wild animals but even stones and woods”: so Quintilian in the <citation>Institutes of oratory</citation>, book 1. Amphion is said to have done something similar to this, on which Horace in his <citation>Odes</citation>: “Amphion moved stones by singing”, and Statius in the <citation>Thebaid</citation>, book 1:\n\
<verse>                                                                with what song<l/>Amphion commanded the Tyrian mountains to be like walls.</verse>\n\
Nay more, the poets, in order to show the greater efficacy of music in respect of softening hardness of heart, imagine Orpheus himself as having moved both the gods and the judges and the monsters of the underworld with his song, on which Virgil in the <citation>Georgics</citation>, book 4, says:\n\
<verse>He entered the jaws of Taenarus, the deep entrance of Dis,<l/>and the grove, reeking with black horror,<l/>and approached the gods of the dead and the terrible king<l/>and the hearts that do not know how to be softened by human entreaties.<l/>And, moved by his song, the faint shades came from the deepest<l/>foundations of Erebus, ghosts of those deprived of light.</verse>\n\
And a little later follows:\n\
<verse>Nay, even the halls of Death and deepest Tartarus were stunned,<l/>and the Eumenides with their hair entwined with dark snakes,<l/>and Cerberus held his three mouths gaping,<l/>and Ixion’s wheel stood still with the underworld’s wind.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the ninth effect. Chapter 9 [ix].</heading>\n\
Ninth: Music puts the devil to flight. Whence in 1 Samuel, chapter 16: “David took his harp and played with his hand, and Saul was refreshed and was better, for the evil spirit departed from him”. On which a rhetorician has also set forth these verses:\n\
<verse>King David calmed the wrath of the demon in Saul,<l/>Showing with a song the harp’s wonderful power.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the tenth effect. Chapter 10 [x].</heading>\n\
Tenth: Music causes ecstasy. Whence, after David sang in the 67th Psalm, “Princes went before joined with singing, in the midst of young damsels playing on timbrels”, a little later he added, “There is Benjamin a youth, in ecstasy of mind.” The Philosopher writes this about it in the <citation>Politics</citation>, book 8: “The melodies of [the 7th-century-BC Phrygian composer] Olympus make souls carried away”. As Quintilian reports in confirmation of this in the <citation>Institutes of oratory</citation>, book 1, “a piper, who had played a Phrygian tune for a sacrificing priest, is stated to be accused of having been the cause of his death, after he was driven mad and leapt off a cliff”.\n\
</chapter>\n\
<chapter>\n\
<heading>On the eleventh effect. Chapter 11 [xi].</heading>\n\
Eleventh: Music lifts up the earthly mind. Whence Bernard on the Song of songs: “The joyful song of praise lifts up the eyes of the heart.” The mind, indeed, is moved by the sweetness of harmony to contemplation of heavenly joys, which is the greatest part of the better life, and hence it forsakes thought of earthly things, which, pertaining to the active life, leads to anxiety and worry.\n\
</chapter>\n\
<chapter>\n\
<heading>On the twelfth effect. Chapter 12 [xii].</heading>\n\
Twelfth: Music restrains ill will. For, as Cicero says in his book <citation>On his deliberations</citation> and Quintilian repeats in the <citation>Institutes of oratory</citation>, book 1: “Pythagoras pacified some young men, who were stirred up to inflict violence on an inoffensive household, by telling the woman piper to change the rhythm to a spondee”.\n\
</chapter>\n\
<chapter>\n\
<heading>On the thirteenth effect. Chapter 13 [xiii].</heading>\n\
Thirteenth: Music gladdens people. For indeed, as Aristotle reports in the <citation>Politics</citation>, book 8: “Musaeus says that singing is the most delightful thing for people; on that account they reasonably adopt it in assemblies and pastimes as having the power to gladden”.\n\
And indeed, it gladdens some more, and others less. For indeed, the more perfected in this art one is, the more one is delighted by it, because one grasps its nature both inwardly and outwardly: inwardly by the power of understanding, by which one understands fitting composition and performance, and outwardly by the power of hearing, by which one perceives the sweetness of concords. But only such are those who can truly judge and be delighted by music itself; on that account the Philosopher in the <citation>Politics</citation>, book 8, advises the young to apply themselves to music, so that not only they may be delighted by the sound produced by themselves or by another, but once they have grown old and given up the practice, they can correctly judge about it.\n\
But music gladdens those less who get nothing at all out of it except the sound. For they are delighted only by the external sense. They are so much affected, however, by such sound that, in Juvenal’s words, “running after a pretty voice”, they proclaim and extol as the best musicians those who sing (as they think) with a delightful voice, even if they perform very crudely. Nor do I wonder when I have read Virgil having sung in the 2nd eclogue of the <citation>Bucolics</citation>: “Each is attracted to their own pleasure”.\n\
The perfection of musical delight, therefore, consists in its perfect knowledge. Whence Aristotle in the <citation>Politics</citation>, book 8, states to the point that “an end”, that is, the perfection of delight in it, “does not accord with the imperfect”.\n\
</chapter>\n\
<chapter>\n\
<heading>On the fourteenth effect. Chapter 14 [xiv].</heading>\n\
Fourteenth: Music heals the sick. Whence Isidore reports in the <citation>Etymologies</citation>, book 4, that “the physician Asclepiades restored a madman to his former health by the art of melody”. Hence the same eminent author says that music is necessary for the physician. This seems demonstrable enough from the sayings of Ibn Sīnā and Galen, of whom the first says: “You must know, however, that in the pulse is found the nature of music”, and the second: “When the nature of musical proportions was made known to me, then the gates of the pulse were opened to me.”\n\
</chapter>\n\
<chapter>\n\
<heading>On the fifteenth effect. Chapter 15 [xv].</heading>\n\
Fifteenth: Music lightens labours. For, as Quintilian has it in the <citation>Institutes of oratory</citation>, book 1, “nature herself seems to have given us music to endure labours more easily, since songs cheer even oarsmen”. Virgil writes about this in the 9th eclogue of the <citation>Bucolics</citation>: “we can go along singing (the way will trouble less)”, and in the <citation>Georgics</citation>, book 1:\n\
<verse>meanwhile, her long labour lightened by a song,<l/>his wife runs through the warp with a rattling reed.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the sixteenth effect. Chapter 16 [xvi].</heading>\n\
Sixteenth: Music rouses the spirits to battle. Hence it is said of Misenus, who, accompanying Hector, most excellently fired up the battle against the siege of Troy with the bugle, that when Misenus, who had followed Aeneas over the seas after Hector died, endeavoured to do it again, he was drowned out of envy by Triton, Neptune’s trumpeter. On which Virgil says in the <citation>Aeneid</citation>, book 6:\n\
<verse>And as they thus came, they saw Misenus<l/>on the dry shore, cut off by unworthy death,<l/>Misenus son of Aeolus, whom no other excelled<l/>in rousing up men with the brass and firing up Mars with a song.<l/>(and the rest that follow there)</verse>\n\
Hence we read that Timotheus, piper of Alexander the Great, repeatedly stirred him up from feasts to war. Quintilian agrees with this in the <citation>Institutes of oratory</citation>, book 1: “It was said that the greatest generals played both lyres and pipes and that the army of the Lacedaemonians were fired up by musical measures.” Such melodies, however, are provocative of anger, as the Philosopher holds in the <citation>Politics</citation>, book 8; the more vigorous they are, the stronger they make the spirits of the fighters (so Isidore in the <citation>Etymologies</citation>, book 3), for which reason they attain in the end the glory of victory. Whence Quintilian in the <citation>Institutes of oratory</citation>, book 1: “What else, indeed, do horns and trumpets do in our legions? The more vigorous their sounding is, the more Roman glory in war excels that of others.”\n\
</chapter>\n\
<chapter>\n\
<heading>On the seventeenth effect. Chapter 17 [xvii].</heading>\n\
Seventeenth: Music entices love. Whence Ovid teaches girls desiring to entice the love of men that they should study singing; and in fact he says in the <citation>Art of love</citation>, book 3:\n\
<verse>Song is an alluring thing: girls should study singing;<l/>    instead of the face, for many the voice has been her procuress.</verse>\n\
Hence it is that it was said by the poets that when Orpheus played the lyre very sweetly, many women were fired with love of him. On which Ovid in the <citation>Metamorphoses</citation>, book 10:\n\
<verse>                    Still, many women had a burning desire<l/>to join themselves with the bard; many, rejected, lamented.</verse>\n\
Nay, the melody of Orpheus’ singing was of such sure efficacy at enticing love that it even compelled pre-pubescent boys to loving, whence there follows in the same place:\n\
<verse>He was even the originator among the peoples of Thrace of transferring<l/>[men’s] love to tender males, and plucking the first flowers<l/>in the brief springtime of the age before youth.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the eighteenth effect. Chapter 18 [xviii].</heading>\n\
Eighteenth: Music increases the enjoyment of a banquet. Whence in Ecclesiastes, chapter 32: “A concert of music in a banquet of wine is as a carbuncle set in gold.” The gloss: “The carbuncle compares to the gold, and the musical melody to the banquet; indeed, just as a carbuncle doubles the splendour of gold, so does melody the enjoyment of a banquet.”\n\
Hence the poets say that music was accepted at the feasts of the gods. Whence Horace writes in his <citation>Odes</citation>:\n\
<verse>O lyre, ornament of Phoebus and welcome<l/>at the grandest dinners of Jove, O sweet<l/>alleviation of labours, greet me whenever<l/>    I duly call!</verse>\n\
But from of old it has been not uncommon for illustrious people to take up music when feasting. Whence Virgil, reciting what had taken place at the sumptuous banquet prepared by Elissa for Aeneas with his companions, cites Iopas, a most skilful harper, as striking the harp so that it would be more enjoyable; on which in the <citation>Aeneid</citation>, book 1: “Long-haired Iopas sounds the gilded harp” (and the rest). “It was also the custom of the earlier Romans to employ lyres and pipes at feasts”; so Quintilian in the <citation>Institutes of oratory</citation>, book 1. And in Isaiah, chapter 5, we read: “The harp, and the lyre, and the timbrel, and the pipe, and wine are in your feasts”.\n\
We also see this custom thriving very much at this time: when great men are feasting splendidly and solemnly, what kind of musicians do we not hear present? There singers, there pipers, there drummers, there organists, there harpers, there recorders, there trumpets, making music together so melodiously that it seems to be a true image of heavenly joys.\n\
</chapter>\n\
<chapter>\n\
<heading>On the nineteenth effect. Chapter 19 [xix].</heading>\n\
Nineteenth: Music glorifies those skilled in it. Whence in Ecclesiastes, chapter 44: “Men such as by their skill sought out musical tunes have gained glory in their generations, and were praised in their days.”\n\
And because long ago in Greece musicians used to be honoured with the greatest glory on account of the “greatest accomplishment” that “the Greeks considered to be placed in those making music of strings and voices”, not only the most excellent philosophical men bestowed care on it, like Socrates, Pythagoras, Plato, Aristotle, but also the most warlike rulers, like Epaminondas and Achilles. “And Themistocles, when he refused the lyre at a feast, was deemed rather uneducated”. Moreover, Cicero also states, along with the preceding, in the prologue of the <citation>Tusculan disputations</citation>: “everyone used to study it, and whoever was ignorant of it was not considered sufficiently cultivated in learning”.\n\
In our time, however, we know from experience how much glory most musicians have been honoured with. For who has not heard of John Dunstaple, Guillaume du Faÿ, Gilles Binchois, Johannes Okeghem, Antoine Busnoys, Johannes Regis, Fremin Caron, Robert Morton? Who does not bestow the highest praises on them, whose compositions, renowned throughout the world, fill God’s temples, kings’ palaces, the houses of private people with the greatest sweetness? I pass over many distinguished musicians endowed with riches and titles, since even though they have acquired honours from these, they are by no means to be compared with the undying fame that the first composers have spread about for themselves. For the former thing needs luck, the latter talent; whence Virgil in the <citation>Aeneid</citation>, book 10:\n\
<verse>To each his day is due; life lasts a brief and irretrievable time<l/>for everyone. But to spread about one’s fame with deeds,<l/>this needs talent.</verse>\n\
</chapter>\n\
<chapter>\n\
<heading>On the twentieth effect. Chapter 20 [xx].</heading>\n\
Twentieth: Music blesses souls. For there is no doubt that people are led to remorse by hearing song; indeed, on this account the Church has established the praises of God to be sung, as is clear from [the <citation>Decretals of Gratian</citation>, part I,] distinction 21, chapter 1, and from the Holy Doctor [Thomas Aquinas] in the Second part of the second part [of the <citation>Summa theologiae</citation>], question 91, article 2. Whence, since souls attain salvation through remorse, it follows that music is the cause of such salvation. This salvation, indeed, is the greatest blessing, which is attained not only, as we have said, by those who hear music, but also by those who understand it. Whence the prophet in the 88th Psalm: “Blessed is the people that knoweth jubilation.”\n\
</chapter>\n\
<conclusion>\n\
<heading>Conclusion of the work.</heading>\n\
If anyone, therefore, pays attention to these effects, they will not repent having applied their intelligence to this element of learning; nay rather, every day with the most ardent devotion they will study melody, which for kings, which for other rulers, and which for free people it is glorious and commendable to have practised and to practise. For it is this that is approved and recommended by Lycurgus, Plato, Quintilian; if anyone follows their recommendations, both the art will be a credit to them and they to the art forever.\n\
</conclusion>\n\
<explicit>Here ends the <citation>Encompassing of the effects of music</citation>.</explicit></treatise>';