texts.dealterationenotarum = {};
if(!texts.treatises) texts.treatises = [];
texts.treatises.push("dealterationenotarum");
texts.dealterationenotarum.exportYear = 2015;
texts.dealterationenotarum.exportMonth = 12;
texts.dealterationenotarum.exportDay = 10;
texts.dealterationenotarum.exportHour = 12;
texts.dealterationenotarum.exportMinutes = 41;
texts.dealterationenotarum.sources = [['V', 'E-VAu 835, fols. 66v–70r'],
['BU', 'I-BU 2573, fols. 75r–79r'],
['Br1', 'B-Br II 4147 Mus., fols. 44va-47ra'],
['G', 'B-Gu 70, fols. 168vb-171va']];
texts.dealterationenotarum.edited = 'De alteratione notarum\n\
Editor: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 6 August 2015\n\
Base file: De alteratione notarum (BU).txt\n\
Sources:\n\
V	E-VAu 835, fols. 66v–70r (modern numeration)\n\
BU	I-BU 2573, fols. 75r–79r (modern numeration)\n\
Br1	B-Br II 4147 Mus., fols. 44va-47ra\n\
G	B-Gu 70, fols. 168vb-171va (modern numeration)\n\
<treatise><title>{var=(ins.) "nunc" V BU : "Incipit tr. feliciter" G} {var="Tractatus" Br1 : "tractatulus" G : (om.) V BU} {var="De {var="alteratione" V V^i BU BU^i : "alterationibus" G} {var=(ins.) "ipsarum" BU^i} {var="notarum" V^i BU^i : "earundem" V BU}" V V^i BU BU^i G : "alterationum" Br1} {var=(ins.) "incipit" V BU : "tr. feliciter incipit" G}: {var="editus a magistro {var="Joanne" (ed.) : "Johanne" Br1} Tinctoris in legibus licentiato regis{ }que Magne Sicilie capellano" Br1 : (om.) V BU G}</title>\n\
<prologue><heading>{var="{¶ } Prologus." V BU Br1 : (Prologus om. altogether) G}</heading>\n\
Sanctissimo legum interpreti suavissimo{ }que Musarum cultori Guillelmo Guinandi{ ,}**The dedicatee must be Antonius Guinati, who was “abbot” or master of the ducal chapel of Milan from 16 November × 12 December 1472 until at least 7 January 1492 (Merkley and Merkley, 36–8, 87 n. 1, 392, et passim); he was identified as a doctor of laws in notarial acts (ibid., 105, 117, 296; cf. 195 n. 129, 295). One Guillelmus Giggardi was a tenorist in the Milanese chapel in 1473–4 (ibid., 88–9, 101–2, 116, 135–6), perhaps accounting for the mistaken first name of Tinctoris’s dedicatee. Relations between Naples and Milan were extremely strained from January 1473 until late 1474 owing to Galeazzo Maria Sforza’s recruiting singers from Ferrante’s chapel, including the soprano Jehan Lothin (dedicatee of Tinctoris’s <citation>Expositio manus</citation>) and the celebrated tenorist Jehan Cordier (ibid., 41–57; esp. 45 with n. 31 (Johannes “de Divanto” must be a misreading of “de Dinanto”, i.e. Lothin), 53–7); <citation>De alteratione</citation> was probably written somewhat later, after the repercussions of this affair had died away. Alternatively, Tinctoris may have dedicated the treatise to Guinati as the only lawyer/musician he could think of, and the frosty relations might account for the mistaken name. (Lothin was still (or again) in the Neapolitan chapel in October 1480: Vander Straeten, iv: 28–30, where the vernacular form of his surname is given.)** {var="protocapellano" V BU^c : "prothocapellano" BU^* Br1} serenissimi ducis Mediolani{:,} {var="_Joannes" V BU : "Johannes" Br1} Tinctoris{ ,} inter legum ac artium mathematicarum studiosos minimus{:,} honorem perpetuum{ }que decus. Nuper (egregie vir) meas usque ad aures rumor subvolavit quendam cantorem tuo subiectum imperio me palam asseruisse circa quandam alterationem musicam errasse{.,} eo quod{ ,} quom in manibus suis habuisset officium nostrum {var="iam" V BU : "ia" Br1} olim super <citation>Nos amis</citation> editum{.,} in ipso sub tempore perfecto{. } inter duas breves duas semibreves quarum ultima non alteratur hoc in modo {var="reperisset" V BU : "repperisset" Br1}:\n\
<example: {full measure}, {mensural: void}, {staf: "5" (ed.) : "4" V BU : "3" Br1, red}> {clef: "F8" BU : "F6" V Br1} {solm: 0} {mens: O9} PS9_PS9 Ba mG mF SE BD || </example>\n\
{¶ } In quo se admodum esse rusticum ostendit{ ,} non advertens alterationem aliquam non debere fieri ubi nullus est defectus numeri. {var="Eius" V BU : "Cuius" Br1} licet rusticitati (hoc etenim iura precipiunt) sit parcendum{.,} non tamen obiectum errorem ne tacendo huic consentire videar impurgatum censui {var="relinquendum" BU Br1 : "reliquendum" V}. Quamobrem hoc opusculum edidi et quicquid de notarum alterationibus sentiam in eo posui{.,} ut{ ,} quom id perlegere dignatus fueris{ ,} me reprehensum inique {var="percipias" V : "precipias" BU Br1}{.,} et adversus calumniatorem{. } pro veritate certando (quod proprium est viri fortis) tuearis et protegas.</prologue>\n\
<chapter><heading>{var="{¶ } Quid sit alteratio. Capitulum .i." V BU Br1 : (om.) G}</heading>\n\
<definition><lemma: alterationis, alteratione, alterationem, alterationi, alterationes, alterationum, alterationibus>Alteratio</lemma> est proprii valoris alicuius note duplicatio.</definition> Notam etenim alterari {var="nihil" V BU : "nichil" Br1} aliud est{. } quam cum suo proprio valoris alterius similis effici. Hinc circa notarum alterationem primo generaliter versando octo generales regulas {var="tradere proposui" V BU Br1 : "trademus" G}.\n\
<subheading>{¶ } Prima {var="generalis {var="regula" Br1 : "regularis" V BU}" V BU Br1 : "regula alterationum" G}.</subheading>**The error “regularis” probably stood in Tinctoris’s original.**\n\
Prima generalis regula est quod {var="ubicunque" V^c G : "ubicumque" V^* : "ubicūq;" BU Br1} due note eiusdem speciei ternario numero subiecte inveniuntur sole{.,} ultima earum alteratur. {¶ } Due autem note huiusmodi sole inveniri dicuntur quando non {var="habent" BU Br1 G : "abent" V} aliquam similem continuam aut sincopatam precedentem que cum illis {var="numerari possit" V BU Br1 : "possit numerari" G}. {var="Nanque" V : "Nāq;" BU : "Namq;" Br1 G} si aliqua similis que cum illis numerari possit{. } continue vel per sincopam precedat{.,} tunc omnes tres connumerabuntur{.,} et eo quod “cessante causa cesset effectus”{.,}**Legal maxim, originating in the 12th century; see André Gouron, “<italic>Cessante causa cessat effectus</italic>: à la naissance de l’adage”, <italic>Comptes rendus des séances de l’Académie des Inscriptions et Belles-Lettres</italic>, 143 (1999), 299–309.** cessante numeri imperfectione cessabit alteratio{.,} {var="ut hic patet" V : "ut patet in sequenti exemplo" BU : "ut hic" Br1 : (om.) G}:\n\
<example: {full measure}, {mensural: void}, {staf: "5" V BU G : "4" Br1, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: Ø7}PL5-9x3MG <lig>LF LG</lig> Ma LD <lig>BE BF</lig> LG Ba <lig>SG Sb</lig> Sc Bd Sc mb_{var=".11" V BU G : (om.) Br1} {var=(ins.) "{staf: 3} {clef: C8} {solm: 0}" Br1} mG ma SG LD <lig><obl>BG BF</obl></lig> SG. ma Sb. mc md SG La MG || </example>\n\
{¶ } Dupliciter autem contingere potest quod due note ternario numero subiecte similem non habeant precedentem que cum illis numerari possit: primo {var=(ins.) "scilicet" G}{ ,} quando realiter nulla precedit{.;} secundo{ ,} quando aliqua precedit{ ,} sed impletione ad alium locum reduci ostenditur{.,} vel ab illis puncto dividitur{.,} ut hic:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C8} <label>Exemplum.</label> {solm: 0} {mens: Ø11}PL7-11x3 <lig><obl>{var="Bg" V BU Br1 : "Bf" G} Be</obl></lig> Md Le {full}Bf <lig><obl>{var="Bd" V BU Br1 : "Be" G} Bc</obl></lig> {full}Ld BG. Sb. <lig>Sa Sb Bc</lig>. {var=(ins.) "{staf: 5} {clef: C10} {solm: 0}" Br1} Sd mc ma mb Lc <lig><obl>Bb BG</obl> Ba</lig> {var="MG" V BU Br1 : "-LG" G} || </example>\n\
<subheading>{¶ } Secunda {var="generalis regula" V BU Br1 : "regula generalis alterationum" G}.</subheading>\n\
Secunda {var="generalis regula" V BU Br1 : "regula generalis" G} est quod non refert si due note sole invente{. } quarum ultima venit alteranda sint continue aut sincopate{.,} quia dum in istis sicut in illis requiritur perfectio{.;} consequenter accidit alteratio{.,} {var="sicut hic" V BU Br1 : "ut in exemplo subsequenti" G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C8} <label>Exemplum.</label> {solm: 0} {mens: Ø9}PL7-11x3 Md <lig>Le Lg</lig> {var=(ins.) "." G} Mf. Le Md. Lc Md {var=(ins.) "{staf: 5} {clef: C10} {solm: 0}" Br1} LG <lig>Ba Bb</lig> Lc. Sd Bc. Sb Ba {var="MG" V BU Br1 : "-LG" G} || </example>\n\
<subheading>{¶ } {var="Tertia" V BU^c : "Tercia" BU^* Br1 G} {var="generalis regula" V BU Br1 : "regula generalis" G}.</subheading>\n\
{var="Tertia" V : "Tercia" BU Br1 G} {var="generalis regula" V BU Br1 : "regula generalis" G} est quod omnis nota que alteratur{. } necessario ante suam maiorem propinquam alteratur{.,} ut longa ante maximam{.,} brevis ante longam{.,} semibrevis ante brevem{.,} et minima ante semibrevem. Cuius ratio duplex est: prima {var=(ins.) "quidem" G}{ ,} quoniam loco note alterande maior propinqua poni non potest{.,} eo quod similis ante similem {var="non imperficitur" V BU Br1 : "imperfici non possit" G}{.,} unde que per alterationem valet {var="tantummodo" V BU Br1 : "tantum" G} duas necesse {var="valeret" BU Br1 G : "valet" V} tres{.,} ad quod evitandum secunda prime similis est alterabilis. Secunda {var="ratio est" V BU Br1 : "est ratio" G}{.,} quoniam due note minores eiusdem speciei ante maiorem remotam aut remotiorem aut remotissimam posite{.,} ut due breves ante maximam{.,} {var=(ins.) "vel" G} due semibreves ante longam{.,} {var=(ins.) "vel" G} due minime ante brevem{.,} {var="aut" V BU Br1 : "vel" G} due semibreves ante maximam{.,} {var=(ins.) "vel" G} due minime ante longam{.,} {var="aut" V BU Br1 : "vel" G} due minime ante maximam{.,} possunt eam imperficere{.;} et sic absque alteratione numerus est in perfectione{.,} {var="ut hic patet" V BU : "ut hic" Br1 : "ut hic. in exemplo subsequenti" G}:**V BU G uniformly break the staff after the ligature ending with a maxima, suggesting that Tinctoris’s original did likewise.**\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exem{var=(ins.) "Exem" Br1}plum{var=(ins.) "tertie regule generalis" BU : (ins.) "Exemplum. Exemplum." G}.</label> {solm: 0} {var="{mens: Ø5}PL5-9" V BU Br1 : "PL5-9{mens: Ø7}" G} MD <lig>LE LD</lig> MG. BF <lig>LG La</lig> <lig>Bb Bc</lig> Ld Bc <lig><obl>Sb SG</obl> Ba</lig> LG LD <lig>BE BF</lig> SG ma mb Sc Ld. {var=(ins.) "{staf: 5} {clef: C12} {solm: 0}" Br1} <lig><obl>Bb BG</obl> Ma</lig> c {staf: 5} {clef: C10} {solm: 0} LD. <lig>SG SF LE</lig> BF. mD mE BF <lig>Sa Sb</lig> Sc <lig><obl>Sd Sb</obl></lig> Ma Lb. ma mb Lc <lig>BG Ba Bb</lig>. mG ma MD <lig>LG Lb</lig> La MG || </example>\n\
<subheading>{¶ } Quarta {var="generalis regula" V BU Br1 : "regula generalis" G}.</subheading>\n\
Quarta {var="generalis regula" V BU Br1 : "regula generalis" G} est quod{ ,} licet duas notas minores ante {var="maiorem" V BU Br1 : "minorem" G} propinquam solas inventas alia maior remota vel remotior vel remotissima ab illis duabus imperfectibilis {var="precedat" V BU Br1 : (om.) G}{.,} tamen{ ,} eo quod imperfectio {var="tanquam" G : "tāq(uam)" V BU : "tamq(uam)" Br1} odiosa magis quam alteratio sit evitanda{.,} non hec ab illis imperficietur{.;} {var="immo" V BU Br1 : "ymmo" G} ultima illarum alterabitur{.,} nisi puncto abinvicem vel ambe ab ipsa maiore propinqua dividantur{.,} {var="ut patet {var="in sequenti" BU : "impresenti" V} exemplo" V BU : "ut hic" Br1 : "ut hic in exemplo sequenti" G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C8} <label>Exemplum.</label> {solm: 0} {mens: Ø5}PL5-9x3 MG <lig>Bb Bc La</lig> Md <lig>Se Sf <obl>Bg {var="Bd" V BU Br1 : "Be" G}</obl></lig> Mf md me <lig><obl>Sd Sc</obl></lig> {var=(ins.) "{staf: 5} {clef: C10} {solm: 0}" Br1} Ld Sb{var="." BU Br1 G : (om.) V} SG Ba mF mG_.7 <lig>Sa Sb Bc</lig> Ld <lig>Bb Bc BG La</lig> LG || </example>\n\
<subheading>{¶ } Quinta {var="generalis regula" V BU Br1 : "regula generalis" G}.</subheading>\n\
Quinta {var="generalis regula" V BU Br1 : "regula generalis" G} est quod omnis nota veniens alteranda quo ad formam necessario est integra. Eius vero socia per partes potest esse divisa{.,} {var="ut hic" BU Br1 : "ut hic patet" V : "ut in exemplo sequenti" G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: Ø11}PL7-11 Md <lig><obl>Bc {var="Bb" V BU G : "Ba" Br1}</obl></lig> SG mF mG ma <lig><obl>SF SD</obl></lig> LE MD <lig>LG {var="LE" V BU Br1 : "LF" G}</lig> BF. {var="<lig><obl>SG SF</obl></lig>" V BU G : "<lig>SG SF</lig>" Br1} SG Ba LG Bc. ma mb Sc Bd SG mE .7 {void}sD {var="{void}sE" V BU Br1 : "mE" G} mF SG. mb Sa LG || </example>\n\
<subheading>{¶ } Sexta {var="generalis regula" V BU Br1 : "regula generalis" G}.</subheading>\n\
Sexta {var="generalis regula" V BU Br1 : "regula generalis" G} est quod{ ,} licet pause loco notarum sociarum alterandarum aut {var="partium" V BU G : "parcium" Br1} suarum habeant vim {var="inducendi" V BU Br1 : "reducendi" G} alterationem{.,} nulla tamen alterari potest{.,} {var="ut hic" Br1 G : "ut hic patet" BU : "ut patet impresenti exemplo" V}:**This music example must have been difficult to read in Tinctoris’s original; the copying errors in V BU G are more plentiful and stranger than in any other example in the mensural treatises, and even the scribe of Br1 (which has it nearly correct) overlooked a dot of perfection.**\n\
<example: {full measure}, {mensural: void}, {staf: "5" Br1 G : "4" V BU, red}> {clef: "C10" V Br1 G : "C10 [C8]" BU} <label>Exemplum. {var=(ins.) "Exemplum." G}</label> {solm: 0} {mens: Ø7}PL5-9x3_PL7-11 Ld MG La PB7 BF LG MD{var="." V BU G : (om.) Br1} BE PS5 SE BF LG Sa Pm9 ma Sb <lig>Bc Bd</lig> <lig>LG La</lig> LG {var=(ins.) "{staf: 5} {clef: C10} {solm: 0}" BU} {var="{mens: C11}" V BU Br1 : "Ld" G}PL7-11x3 {var="Ld" BU Br1 G : "Lb" V} PL7-11 {var=(ins.) "{staf: 5} {clef: C10} {solm: 0}" V} {var="MG" BU Br1 G : "{2halffull}MG" V} La {var="BF" BU Br1 G : "BG" V} PB7 {var=(ins.) "{staf: 5} {clef: C12} {solm: 0}" Br1} LG {mens: O5} MD BE SE PS5 BF <lig>SG Sa</lig> Sb <lig>La LG</lig> {mens: Ø5} <lig>BD {var="BF" V Br1 G : "BG" BU}</lig> <lig>{var="SG" V Br1 G : "SF" BU} Sa</lig> ma Pm9 Sb <lig>Bc Bd</lig> Sb. {var="SG" V BU Br1 : "mG" G} Ba LG || </example>\n\
{¶ } Preterea talis ante pausas perfectas fit alteratio qualis ante notas quibus sunt appropriate{.;} hinc {var="fit" V BU Br1 : "est" G} ut ante pausam longe in modo minori perfecto alteretur brevis{.,} ante pausam brevis in tempore perfecto semibrevis{.,} et ante pausam semibrevis in {var="maiori prolatione" V BU Br1 : "prolatione maiori" G} minima{.,} {var="ut hic patet" BU Br1 : "ut hic" V : "ut patet hic &c." G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum{var=(ins.) "plum" Br1}.</label> {solm: 0} {mens: Ø7}PL7-11x3 <lig>LG La</lig> Lb <lig>Bc Bd</lig> PL7-11x2 LG BF BG <lig><obl>SE SD</obl></lig> PB5 LF <lig>SG Sa</lig> mb mG PS7 <lig><obl>Sa SF</obl></lig> SG Ba {var="MG" V BU Br1 : "LG" G} || </example>\n\
<subheading>{¶ } Septima {var="generalis regula" V BU Br1 : "regula generalis" G}.</subheading>\n\
Septima {var="generalis regula" V BU Br1 : "regula generalis" G} est quod ligatura non facit alterationem{.;} unde si tres note minores inveniantur ante maiorem propinquam quarum due ultime sunt colligate ac etiam ipsi maiori colligate{.,} licet aliqua maior propinqua vel remota vel remotior eas precedat que a prima earum posset imperfici{.,} tamen{ ,} eo quod imperfectionem atque alterationem quantum possumus propter improprietatem {var="utriusque" V BU Br1 : "veriusque figere" G} fugere debemus{.,} ultima non alteratur{.;} {var="immo" V BU Br1 : "ymmo" G} cum duabus primis numeratur{.,} nisi puncto {var=(ins.) "puncto" BU^* : (del.) BU^c} a duabus ultimis prima dividatur{.,} {var="ut hic patet" V Br1 : "ut patet insequenti exemplo" BU : "ut patet in exemplo subsequenti" G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: O7}PL5-9x3 MG {var="LF <lig>LG La</lig>" BU Br1 G : "<lig>LF LG</lig> La" V} <lig>MG Md</lig> Bb <lig>BG Ba LD</lig> LG ME SF <lig>SG Sa</lig> <lig>Bb Bc</lig> Bd Sc .9 <lig><obl>Sb SG</obl> Ba</lig> {var="LG" V BU Br1 : "-MG" G} || </example>\n\
{¶ } Talis {var="attamen" V BU Br1 : "tamen" G} colligationis modus{ ,} nisi fiat propter dicta supposita{.,} plurimum est fugiendus{:;} multo nempe convenientius aut nulle talium trium notarum{ ,} aut omnes{ ,} aut prima {var="et" V BU Br1 : "aut" G} secunda colligantur{.,} {var="ut hic patet" V BU : "ut hic" Br1 G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: O7}PL5-9x3 MG LF LG La <lig>MG Md</lig> <lig><obl>Bb BG</obl> Ba</lig> LD LG ME <lig>SF SG</lig> Sa Bb Bc Bd Sc {var=".9" V BU Br1 : (om.) G} <lig><obl>Sb SG</obl> Ba</lig> LG || </example>\n\
<subheading>{¶ } Octava {var="generalis regula" V BU Br1 : "regula generalis" G}.</subheading>\n\
Octava {var="generalis regula" V BU Br1 : "regula generalis" G} est quod omnis nota ternario numero subiecta est alterabilis{.;} unde{ ,} {var="quom" V BU Br1 : "cum" G} longa in modo maiori perfecto{.,} brevis in modo minori {var="perfecto" V BU : "imperfecto" Br1 G}{.,} semibrevis in tempore perfecto{.,} et minima in prolatione maiori{. } numero ternario sint subiecte{.,} in ipsis quantitatibus veniunt alterande. De quarumquidem alterationibus{.,} ut clarius {var="intelligatur" V BU Br1 : "intelligantur" G}{.,} nunc particulariter {var="tractare proposuimus" V BU Br1 : "tractabimus" G}.</chapter>\n\
<chapter><heading>{¶ } De alteratione longe. Capitulum .ii.</heading>\n\
Si due longe sole in modo maiori perfecto ante maximam inveniantur{.,} ultima {var="illarum" V BU Br1 : "earum" G} alteratur{.,} {var="ut patet in {var="sequenti" BU : "presenti" V} exemplo" V BU : "ut in exemplo sequenti" G : "ut hic patet" Br1}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: O5}PL5-9x3 MD <lig>LG La</lig> MG. La Mb. Lc Md <lig>LG La Lb</lig> <lig>Lc La</lig> MG || </example>\n\
<subheading>{¶ } De alteratione brevis.</subheading>\n\
Si due breves sole in modo minori perfecto ante longam aut eius pausam inveniantur{.,} ultima illarum alteratur{.,} {var="ut patet in {var="sequenti exemplo" V BU : "exemplo subsequenti" G}" V BU G : "ut hic" Br1}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: C7}PL5-9x2 <lig><obl>BG BE</obl></lig> LD <lig>BE BF</lig> PL5-9 LG Ba .7 <lig><obl>BF BE</obl></lig> BD <lig>BF BG</lig> <lig>La Bd</lig> .11 <lig>BG Ba BF BG Ba</lig> PL7-11 Ld <lig>BG <obl>Bb {var="Ba" V BU Br1 : "BG" G}</obl></lig> LG || </example>\n\
<subheading>{¶ } De alteratione semibrevis.</subheading>\n\
Si due semibreves sole in tempore perfecto ante brevem aut eius pausam inveniantur{.,} ultima illarum alteratur{.,} {var="ut patet in {var="{var="sequenti" BU : "presenti" V} exemplo" V BU : "exemplo subsequenti" G}" V BU G : "ut hic" Br1}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: Ø11}PL9-11 Bd <lig><obl>Sb Sa</obl></lig> BG <lig>Sa Sb</lig> PB9 BG. Sa BF. SE <lig>BD Ba</lig> <lig>SG Sa</lig> Sb <lig><obl>Sc Sb</obl></lig> Ba <lig>SG Sa</lig> Sb <lig>Sc Sd</lig> PB11 <lig>BG Ba</lig> MG || </example>\n\
<subheading>{¶ } De alteratione minime.</subheading>\n\
Si due minime sole in maiori {var="prolatione" V BU : "prolacione" Br1} ante semibrevem aut eius pausam inveniantur{.,} ultima illarum alteratur{.,} {var="ut hic patet" V BU : "ut hic" Br1 : "ut in exemplo subsequenti patet. Verte" G}:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> {clef: C10} <label>Exemplum.</label> {solm: 0} {mens: Ç5}PL5-7 SD mE mF <lig>SG Sa</lig> mb mc PS9 Sd mc .9 ma mb mc md mG Sa {var=(ins.) "{staf: 4} {clef: C10} {solm: 0}" Br1} mD mF mE mD mF PS5 SG <lig>Sa Sb</lig> Sc md . mb mG Sa mc . mb Sa LG || </example></chapter>\n\
<chapter><heading>{var="{¶ } Operis conclusio. Capitulum .iii." V BU : (om.) Br1: (Conclusio om. altogether) G}</heading>\n\
Itaque sufficienter de ipsis notarum alterationibus tam generaliter quam particulariter tractatum mihi profecto visum est. si tamen aliqua necessaria circa eas pretermiserim{.,} aut falsa preceperim{.,} calumniatorem precor ut illa subiungere aut ista corrigere dignetur. Nanque tunc reprehensione dignum {var="meme" Br1 : "menie" V BU} existimabo ac eum preceptorem auctentissimum hic et ubique predicabo.</chapter>\n\
<explicit>{var=(ins.) "Scriptum de imperfectione notarum musicarum explicit." BU : (ins.) "Explicit tractatulus de alterationibus notarum." G}</explicit></treatise>';
texts.dealterationenotarum.translation = {};
texts.dealterationenotarum.translation.english = 'De alteratione\n\
Translator: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 7 August 2015\n\
<treatise><title>A treatise On the alteration of notes: set forth by Master Johannes Tinctoris, licentiate in laws and chaplain of the king of Great Sicily.</title>\n\
<prologue><heading>Prologue.</heading>\n\
To the most reverend expounder of the laws and the most delightful cultivator of the Muses, Guillelmus Guinandi [<italic>sic</italic>; <italic>recte</italic> Antonius Guinati], First Chaplain of the most serene duke of Milan, Johannes Tinctoris, least among those studious of the laws and mathematical arts, [wishes] honour and abiding esteem. Recently, distinguished sir, the rumour flew even to my own ears that a certain singer subject to your leadership openly claimed that I had erred about a certain musical alteration, on the grounds that, when he had had in his hands our mass set forth some time ago now upon <citation>Nos amis</citation>, he had found in it, under perfect tempus between two breves, two semibreves of which the latter is not altered, in this way:\n\
{example}\n\
In which he shows himself to be altogether a bumpkin, not realizing that an alteration must not be made where there is no deficiency of number. Although he must be excused for his bumpkinishness — for indeed the laws demand this — nevertheless I did not think the error objected should be left unpurged, lest by keeping silent I should seem to agree to this. For this reason I have set forth this little work and placed in it whatever I understand about the alterations of notes, so that, when you have deigned to read it through, you may perceive me to have been unjustly censured, and may, by contending on behalf of the truth (as befits an honourable man), defend and protect me against the malicious prosecutor.</prologue>\n\
<chapter><heading>What alteration is. Chapter 1 [i].</heading>\n\
<definition><lemma: alterations>Alteration</lemma> is the doubling of the proper value of any note.</definition> And indeed, for a note to be “altered” is nothing other than for it to be made up of a second [<italic>alter</italic>] similar value together with its proper one. Hence, reflecting about the alteration of notes first generally, I have decided to propound eight general rules.\n\
<subheading>The first general rule.</subheading>\n\
The first general rule is that wherever two notes of the same kind subject to ternary number are found alone, the latter of them is altered. Two such notes are said to be found alone, however, when they do not have any similar one, continuous or syncopated, preceding that can be counted together with them. For if any similar one that can be counted together with them continuously or through syncopation should precede, then all three will be counted together, and because “when the cause is absent the effect is absent”, when the imperfection of number is absent alteration will be absent, as is clear here:\n\
{example}\n\
It can occur in two ways, however, that two notes subject to ternary number do not have one preceding that can be counted together with them: first, when really none precedes; secondly, when one does precede, but it is shown by being filled in to be returned to another location, or it is divided from them by a dot, as here:\n\
{example}\n\
<subheading>The second general rule.</subheading>\n\
The second general rule is that it does not matter whether the two notes found alone of which the latter is going to be altered should be continuous or syncopated, because perfection is sought as much in the latter as in the former; consequently alteration occurs, just as here:\n\
{example}\n\
<subheading>The third general rule.</subheading>\n\
The third general rule is that every note that is altered is necessarily altered before a neighbouring larger one, as a longa before a maxima, a breve before a longa, a semibreve before a breve, and a minim before a semibreve. The reason for this is twofold: first, since a neighbouring larger one cannot be put in the place of the note to be altered, because like before like is not imperfected, whence the one that through alteration is worth only two will necessarily be worth three, to avoid which the second similar to the first is alterable. The second reason is, since two smaller notes of the same kind placed before one larger at one remove or at two removes or at three removes, as two breves before a maxima, two semibreves before a longa, two minims before a breve, or two semibreves before a maxima, two minims before a longa, or two minims before a maxima, can imperfect it; and so without alteration the number is in perfection, as is clear here:\n\
{example}\n\
<subheading>The fourth general rule.</subheading>\n\
The fourth general rule is that, although two smaller notes found alone before a neighbouring larger one be preceded by another one larger at one remove or at two removes or at three removes and imperfectible by those two, nevertheless, because imperfection, as hateful, is more to be avoided than alteration, it will not be imperfected by them; on the contrary, the latter of them will be altered, unless they should be divided by a dot from one another or both from that neighbouring larger one, as is clear in the following example:\n\
{example}\n\
<subheading>The fifth general rule.</subheading>\n\
The fifth general rule is that every note that is going to be altered is necessarily entire with respect to its form. But its companion can be divided into parts, as here:\n\
{example}\n\
<subheading>The sixth general rule.</subheading>\n\
The sixth general rule is that, although rests in place of companion notes to those to be altered, or of their parts, have the power of inducing alteration, nevertheless none can be altered, as here:\n\
{example}\n\
Moreover, alteration happens before perfect rests just as before the notes to which they are appropriate; hence it happens that a breve is altered before a longa rest in perfect minor modus, a semibreve before a breve rest in perfect tempus, and a minim before a semibreve rest in major prolation, as is clear here:\n\
{example}\n\
<subheading>The seventh general rule.</subheading>\n\
The seventh general rule is that a ligature does not make an alteration. Whence if three smaller notes are found before a neighbouring larger one of which the last two are ligated or even ligated to that larger one, though some larger one, neighbouring or at one remove or at two removes, precede them that could be imperfected by the first of them, nevertheless, because we must shun imperfection as well as alteration as much as we can on account of the impropriety of both, the last is not altered; on the contrary, it is counted together with the first two, unless the first is divided by a dot from the last two, as is clear here:\n\
{example}\n\
But nevertheless such a method of ligation, unless it is done on account of the words underlaid, is very much to be shunned; certainly much more appropriately either none of such three notes, or all, or the first and second are ligated, as is clear here:\n\
{example}\n\
<subheading>The eighth general rule.</subheading>\n\
The eighth general rule is that every note subject to ternary number is alterable; whence, since the longa in perfect major modus, the breve in perfect minor modus, the semibreve in perfect tempus, and the minim in major prolation are subject to ternary number, in those quantities [i.e. mensurations] they are going to be altered. In order that it should be more clearly understood, we now propose to treat particularly concerning the alterations of each.</chapter>\n\
<chapter><heading>On the alteration of the longa. Chapter 2 [ii].</heading>\n\
If two longas are found alone in perfect major modus before a maxima, the latter of them is altered, as is clear in the following example:\n\
{example}\n\
<subheading>On the alteration of the breve.</subheading>\n\
If two breves are found alone in perfect minor modus before a longa, the latter of them is altered, as is clear in the following example:\n\
{example}\n\
<subheading>On the alteration of the semibreve.</subheading>\n\
If two semibreves are found alone in perfect tempus before a breve, the latter of them is altered, as is clear in the following example:\n\
{example}\n\
<subheading>On the alteration of the minim.</subheading>\n\
If two minims are found alone in major prolation before a semibreve, the latter of them is altered, as is clear here:\n\
{example}</chapter>\n\
<chapter><heading>The conclusion of the work. Chapter 3 [iii].</heading>\n\
And so it has certainly seemed to me sufficiently dealt with concerning those alterations of notes both generally and particularly. If, nevertheless, I have omitted anything necessary about them, or I have taught anything false, I beg the malicious prosecutor to add the former or correct the latter. For then I shall consider myself worthy of censure, and here and everywhere I shall proclaim him the most authoritative teacher.</chapter></treatise>';
texts.dealterationenotarum.V = 'De alteratione notarum\n\
Data entry: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 2015 05 15\n\
Base file: Thesaurus Musicarum Latinarum, TINTRAL.TEXT (Seay edn)\n\
Source: E-VAu 835, fols. 66v–70r (modern numeration)\n\
Script: Lettera rotonda, 1 column per page\n\
Running heads: (verso) De alteratione (recto) notarum.\n\
[-1v-] <index>\n\
{red}¶ De alteratione notarum:	<red>Sextus.</red>\n\
</index>\n\
[-66v-] <treatise><incipit><red>nunc{|}de alteratione earundem incipit:</red></incipit>**Incipit follows on directly from explicit “Finit tractatus de imperfectione notarum musicalium”, accounting for wording.**\n\
[-67r-] <prologue>{blue}¶ <red>Prologus.</red>**Heading in last ¼ of first line of following paragraph.**\n\
{7line}{polychrome}SAnctissimo legum interpreti suavissimo que musarum cultori Guillelmo guinandi protocapellano serenissimi ducis mediolani: Joannes tinctoris inter legum ac artium mathematicarum studiosos minimus: honorem perpetuum que decus: Nuper{-.} egregie**Initial ‘e’ apparently written over erasure.** vir meas usque ad aures rumor sub{_}volavit quendam cantorem tuo subiectum imperio me palam asseruisse circa quandam alterationem musicam errasse eo quod quom in manibus suis habuisset, officium nostrum iam olim super nos{_}amis editum. in ipso sub{|}tempore perfecto. inter duas breves duas semibreves{|}quarum ultima non alteratur hoc in modo reperisset.\n\
<example: {right ⅓-column, parallel to first 5 lines of following paragraph}, {mensural: void}, {staf: 4, red}> _||2-12 _{clef: F6} {solm: 0} {mens: O7} PS7_PS7 Ba mG mF SE BD </example>\n\
{red}¶ In quo se ad modum esse rusticum ostendit non advertens alterationem aliquam non debere fieri ubi nullus est defectus numeri: Eius licet rusticitati hoc etenim iura precipiunt sit parcendum. non tamen obiectum errorem ne tacendo huic consentire videar impurgatum censui reliquendum. Quamobrem hoc opusculum edidi{|}et quicquid de notarum alterationibus sentiam in eo posui. ut quom id perlegere dignatus fueris me reprehensum inique percipias. et adversus calumniatorem{-.} pro veritate certando (quod proprium est viri fortis)**Closing parenthesis written over full point.** tuearis et protegas:</prologue>\n\
<chapter> {blue}¶ <red>Quid sit alteratio. Capitulum primum.</red>**Heading in last ⅚ of last line of preceding paragraph.**\n\
{4line}{gold}ALteratio est proprii valoris alicuius note duplicatio. Notam etenim alterari nihil aliud est. quam cum suo proprio valoris alterius similis effici. Hinc circa notarum alterationem primo generaliter versando octo generales regulas tradere proposui:\n\
<red>-¶ Prima generalis regularis:·</red>**Heading in middle ⅔ of last line of preceding paragraph.**\n\
{2line}{blue}PRima generalis regula est quod ubicunque**Word begun “ubicum-”; last minim of ‘m’ immediately erased and “-q;” written over erasure.** due note eiusdem speciei ternario numero subiecte inveniuntur sole. <underscore>ultima earum alteratur:</underscore>**Underscoring added by same hand as the marginal sign.** <marg: fore (right><newhand: late 15th / 16th century; ?corrector; responsible for underscore>:~</newhand></marg> {blue}¶ Due autem [-67v-] note huiusmodi sole inveniri dicuntur quando non abent aliquam similem continuam aut sincopatam precedentem que cum illis numerari{|}possit: Nanque si aliqua similis que cum illis numerari possit. continue vel per sincopam precedat. tunc omnes tres connumerabuntur. et eo quod cessante causa cesset effectus. cessante numeri imperfectione cessabit alteratio: ut hic patet:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} {mens: Ø7}<label>{blue}¶ <red>Exemplum</red></label>PL5-9x3MG <lig>LF LG</lig> Ma LD <lig>BE BF</lig> LG Ba <lig>SG Sb</lig> Sc Bd Sc mb_.11 mG ma SG LD <lig><obl>BG BF</obl></lig> SG. ma Sb. mc md SG La MG_ </example>\n\
{red}¶ Dupliciter autem contingere potest quod due note ternario numero subiecte similem non habeant precedentem que cum illis numerari possit. primo quando realiter nulla precedit. secundo quando aliqua precedit sed impletione ad alium locum reduci ostenditur. vel ab illis puncto dividitur. ut hic\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} {solm: 0} {mens: Ø11}PL7-11x3 <label>  {blue}¶<red>Exemplum.</red></label> <lig><obl>Bg Be</obl></lig> Md Le {full}Bf <lig><obl>Bd Bc</obl></lig> {full}Ld BG. Sb. <lig>Sa Sb Bc</lig>. Sd mc ma mb Lc <lig><obl>Bb BG</obl> Ba</lig> MG [-] | [-] </example>\n\
 <red>Secunda generalis regula.</red>**Heading in last ⅖ of first line of following paragraph.**\n\
{2line}{red}SEcunda generalis regula{|}est. quod non refert si due note sole invente. quarum ultima venit alteranda sint continue aut sincopate. quia dum in istis sicut in illis requiritur perfectio consequenter accidit alteratio sicuthic.**‘t’ apparently written in immediately afterwards by original scribe.**\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} {solm: 0} {mens: Ø9}<label> <red>¶ Exemplum.</red></label>PL7-11x3 Md <lig>Le Lg</lig> Mf. Le Md. Lc Md LG <lig>Ba Bb</lig> Lc. Sd Bc. Sb Ba MG [-] |3-12 [-][-] </example> <catchword: downwards at foot against rule for back margin; groups of three dots before, after, and above and below centre>tertia</catchword>\n\
[-68r-] <red>¶ Tertia generalis regula:·</red>\n\
{2line}{blue}TErtia generalis regula est quod omnis nota que alteratur. necessario ante suam maiorem propinquam alteratur. ut longa ante maximam. brevis ante longam. semibrevis ante brevem. et minima ante semibrevem. Cuius ratio duplex est prima quoniam loco note alterande maior propinqua poni non potest. eo quod similis ante similem non imperficitur. unde que per alterationem valet tantummodo duas necesse valet tres. ad quod evitandum{|}secunda prime similis est alterabilis. Secunda ratio est. quoniam due note minores eiusdem speciei ante maiorem remotam aut remotiorem aut remotissimam posite. ut due breves ante maximam due semibreves ante longam. due minime ante brevem aut due semibreves ante maximam. due minime ante longam. aut due minime ante maximam: possunt eam imperficere. et sic absque alteratione numerus est in perfectione: ut hic patet:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{blue}¶<red>Exem</red></label> {solm: 0} _{mens: Ø5}PL5-9 MD <lig>LE LD</lig> MG. BF <lig>LG La</lig> <lig>Bb Bc</lig> Ld Bc <lig><obl>Sb SG</obl> Ba</lig> LG LD <lig>BE BF</lig> SG ma mb Sc Ld. <lig><obl>Bb BG</obl> Ma</lig> c __ {staf: 5} _{clef: C10} {solm: 0} LD. <lig>SG SF LE</lig> BF. mD mE BF <lig>Sa Sb</lig> Sc <lig><obl>Sd Sb</obl></lig> Ma Lb. ma mb Lc <lig>BG Ba Bb</lig>. mG ma MD <lig>LG Lb</lig> La <label><red>plum</red></label> MG </example>\n\
{red}-{blue}¶<red>Quarta generalis{|}regula:</red>\n\
{2line}{red}QUarta generalis regula est quod licet duas notas{|}minores ante maiorem propinquam solas inventas alia maior remota vel remotior vel remotissima ab illis duabus imperfectibilis precedat. tamen eo quod imperfectio tanquam [-68v-] odiosa magis quam alteratio sit evitanda. non hec ab illis imperficietur. immo ultima illarum alterabitur. nisi puncto ab invicem vel ambe ab ipsa maiore propinqua dividantur: ut patet impresenti exemplo:·\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} <label>{blue}¶<red>Exem</red></label> {solm: 0} _{mens: Ø5}PL5-9x3 MG <lig>Bb Bc La</lig> Md <lig>Se Sf <obl>Bg Bd</obl></lig> Mf md me <lig><obl>Sd Sc</obl></lig> Ld Sb SG Ba mF mG_.7 <lig>Sa Sb Bc</lig> Ld <lig><label><red>plum.</red></label> Bb Bc BG La</lig> LG |2-12 </example>\n\
<red>¶ Quinta generalis regula:·</red>\n\
{2line}{blue}QUinta generalis regula est quod omnis nota veniens alteranda quo ad formam necessario est integra: Eius vero socia{|}per partes potest esse divisa: ut hic patet:\n\
<example: {full measure + right ½-column, parallel to following heading and first 6 lines (all but last) of following paragraph}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label><red>¶Exem</red></label> {solm: 0} {mens: Ø11}PL7-11 Md <lig><obl>Bc Bb</obl></lig> SG mF mG ma <lig><obl>SF SD</obl></lig> LE MD <lig>LG LE</lig> BF. <lig><obl>SG SF</obl></lig> SG Ba LG Bc. ma mb c __ {staf: 5} _||0-12 {clef: C10} <label><red>plum.</red></label> {solm: 0} Sc Bd SG mE_.7 <void>sD sE</void> mF SG. mb Sa LG [-] |2-13 [-] </example>\n\
{blue}¶ <red>Sexta generalis regula.</red>\n\
{2line}{red}SExta generalis regula est quod licet pause{|}loco notarum sociarum alterandarum aut partium suarum habeant vim inducendi alterationem nulla tamen alterari potest. ut patet impresenti exemplo:·\n\
<example: {full measure}, {mensural: void}, {staf: 4, red}> _<ll: 1, blind> _{clef: C10} <label><red>¶Exemplum.</red></label> {solm: 0} {mens: Ø7}PL5-9x3 PL7-11 Ld</ll> MG La PB7 BF LG MD. BE PS5 SE BF LG Sa Pm9 ma Sb <lig>Bc Bd</lig> <lig>LG La</lig> LG {mens: C9}PL5-9x3 Lb PL5-9 c ____ [-69r-] {staf: 5} _{clef: C10} <label>{blue}¶<red>Exem-</red></label> {solm: 0} {2halffull}MG La BG PB7 LG {mens: O5} MD BE SE PS5 BF <lig>SG Sa</lig> Sb <lig>La LG</lig> {mens: Ø5} <lig>BD BF</lig> <lig>SG Sa</lig> ma Pm9 Sb <lig>Bc Bd</lig> Sb. <label><red>plum.</red></label> SG Ba LG __ </example>\n\
<red>-¶</red> Preterea talis ante pausas perfectas fit alteratio{|}qualis ante notas quibus sunt appropriate: hinc fit ut ante pausam longe in modo minori perfecto alteretur brevis. ante pausam brevis in tempore perfecto semibrevis: et ante pausam{|}semibrevis in maiori prolatione minima: ut hic.\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{blue}¶<red>Exem</red></label> {solm: 0} {mens: Ø7}PL7-11x3 <lig>LG La</lig> Lb <lig>Bc Bd</lig> PL7-11x2 LG BF BG <lig><obl>SE SD</obl></lig> PB5 LF <lig>SG Sa</lig> mb mG PS7 <lig><obl>Sa SF</obl></lig> SG Ba <label><red>plum</red></label> MG [-] |3-12 [-] </example>\n\
<red>-¶ Septima generalis regula:·</red>\n\
{2line}{blue}SEptima generalis regula est quod ligatura non facit alterationem unde si tres note minores inveniantur ante maiorem propinquam quarum due ultime sunt colligate ac etiam ipsi maiori colligate. licet aliqua maior propinqua vel remota vel remotior eas precedat que a prima earum posset imperfici. tamen eo quod imperfectionem atque alterationem quantum possumus propter improprietatem utriusque fugere debemus. ultima non alteratur. immo cum duabus primis numeratur. nisi puncto a duabus ultimis prima dividatur:· ut hic patet:·\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{blue}¶<red>Exem-</red></label> {solm: 0} _{mens: O7}PL5-9x3 MG <lig>LF LG</lig> La <lig>MG Md</lig> Bb <lig>BG Ba LD</lig> LG ME SF <lig>SG Sa</lig> <lig>Bb Bc</lig> Bd Sc .9 <lig><obl>Sb SG <label><red>plum.</red></label></obl> Ba</lig> LG | </example>\n\
[-69v-] {red}¶ Talis attamen colligationis modus nisi fiat propter dicta supposita plurimum est fugiendus: multo nempe convenientius aut nulle talium trium notarum aut omnes aut prima et secunda colligantur. ut hic patet:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{blue}¶<red>Exem</red></label> {solm: 0} _{mens: O7}PL5-9x3 MG LF LG La <lig>MG Md</lig> <lig><obl>Bb BG</obl> Ba</lig> LD LG ME <lig>SF SG</lig> Sa Bb Bc Bd Sc .9 <lig><obl>Sb SG <label><red>plum</red></label></obl> Ba</lig> LG __ </example>\n\
<red>¶ Octava generalis regula:·</red>\n\
{2line}{blue}OCtava generalis regula est{-.} quod omnis nota ternario numero subiecta est alterabilis. unde quom longa in modo maiori perfecto. brevis in modo minori perfecto. semibrevis in tempore perfecto. et minima in prolatione maiori: numero ternario sint subiecte. in ipsis quantitatibus veniunt alterande: De quarum quidem alterationibus. ut clarius intelligatur. nunc particulariter tractare proposuimus:·</chapter>\n\
<chapter>{blue}¶ <red>De alteratione longe: Capitulum secundum:</red>\n\
{4line}{gold}SI due longe sole in modo maiori perfecto ante maximam inveniantur ultima illarum alteratur. ut patet in presenti exemplo:·\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label><red>¶Exem</red></label> {solm: 0} _{mens: O5}PL5-9x3 MD <lig>LG La</lig> MG. La Mb. Lc Md <lig>LG La Lb</lig> <lig><label><red>plum.</red></label> Lc La</lig> MG [-] |2-12 [-][-] </example>\n\
{blue}¶ <red>De alteratione brevis:·</red>\n\
{2line}{red}SI due breves sole in modo minori perfecto ante{|}longam aut eius pausam inveniantur. ultima illarum alteratur: ut patet in sequenti exemplo:\n\
[-70r-] <example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{blue}¶<red>Exem</red></label> {solm: 0} _{mens: C7}PL5-9x2 <lig><obl>BG BE</obl></lig> LD <lig>BE BF</lig> PL5-9 LG Ba .7 <lig><obl>BF BE</obl></lig> BD <lig>BF BG</lig> <lig>La Bd</lig>. <lig>BG Ba BF BG Ba</lig> PL7-11 Ld <lig>BG <obl>Bb <label><red> plum</red></label> Ba</obl></lig> LG |5-12 [-] </example>\n\
<red>-¶ De alteratione semibrevis:·</red>\n\
{2line}{blue}SI due semibreves sole in tempore perfecto ante{|}brevem aut eius pausam inveniantur: ultima illarum alteratur. ut patet in presenti exemplo:·\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label><red>¶Exem</red></label> {solm: 0} {mens: Ø11}PL9-11 Bd <lig><obl>Sb Sa</obl></lig> BG <lig>Sa Sb</lig> PB9 BG. Sa BF. SE <lig>BD Ba</lig> <lig>SG Sa</lig> Sb <lig><obl>Sc Sb</obl></lig> Ba <lig>SG Sa</lig> Sb <lig>Sc Sd</lig> PB11 <lig><label><red> plum</red></label> BG Ba</lig> MG </example>\n\
{blue}¶ <red>De alteratione minime:</red>\n\
{2line}{red}SI due minime sole in maiori prolatione ante semibrevem aut eius pausam inveniantur ultima illarum alteratur: ut hic patet:·\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label><red>¶Exem</red></label> {solm: 0} _{mens: Ç5}PL5-7 SD mE mF <lig>SG Sa</lig> mb mc PS9 Sd mc .9 ma mb mc md mG Sa mD mF mE mD mF PS5 SG <lig>Sa Sb</lig> Sc md . mb mG Sa <label><red>  plum.</red></label> mc . mb Sa LG [-] </example></chapter>\n\
<conclusion>{blue}¶ <red>Operis conclusio:</red>\n\
{4line}{gold}ITaque sufficienter de ipsis notarum alterationibus tam generaliter quam particulariter tractatum mihi profecto visum est. si tamen aliqua necessaria circa eas pretermiserim. aut falsa preceperim: calumniatorem precor ut illa sub iungere aut ista corrigere dignetur. Nanque tunc reprehensione dignum menie existimabo ac eum preceptorem auctentissimum hic et ubique predicabo:·</conclusion></treatise>\n\
';
texts.dealterationenotarum.BU = 'De alteratione notarum\n\
Data entry: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 2015 05 15\n\
Base file: De alteratione notarum (V).txt\n\
Source: I-BU 2573, fols. 75r–79r (modern numeration)\n\
Script: Lettera rotonda, 1 column per page\n\
Running heads: (verso) De alteratione (recto) notarum\n\
[-2v-] <index>\n\
{blue}¶ De alteratione ipsarum notarum:\n\
</index>\n\
[-75r-] <treatise><incipit><red>nunc de alteratione earundem incipit:</red></incipit>**Incipit follows on directly from explicit “Finit tractatus de imperfectione notarum musicalium”, accounting for wording.**\n\
<prologue><red>Prologus</red>**Heading in last ¼ of first line of following paragraph.**\n\
{6line}{polychrome}SAnctissimo legum interpreti suavissimo que musarum cultori{-.} Guillelmo guinandi**Name begun “guinam-”; top of last minim of ‘m’ immediately erased and “-di” written over by original scribe.** prot{expunction}hocapellano serenissimi ducis mediolani: Joannes**Name originally written with lowercase initial; uppercase ‘J’ written over by original scribe.** tinctoris{-.} inter legum ac artium mathematicarum studiosos minimus: honorem{-.} perpetuum que decus. Nuper{-.} egregie vir meas usque ad aures rumor sub volavit quendam cantorem tuo subiectum{|}imperio{-.} me palam asseruisse{-.} circa quandam alterationem musicam errasse eo quod{-.} quom in manibus suis habuisset officium nostrum iam olim super{|}nos amis editum. in ipso sub tempore perfecto. inter duas breves duas**‘s’ apparently written belatedly in word space by original scribe.** semibreves quarum ultima non alteratur hoc in modo reperisset:\n\
<example: {left ⅓-column, parallel to first 4 lines of following paragraph}, {mensural: void}, {staf: 4, red}> _{clef: F8} {solm: 0} {mens: O9} PS9_PS9 Ba mG mF SE BD | [-] |_ </example>\n\
{red}¶ In quo se ad modum esse rusticum ostendit non advertens alterationem aliquam non debere**Word originally written with an illegible letter in place of “-re”; erased and “-(re)” abbreviation sign written over 2nd ‘e’ by original scribe.** fieri ubi nullus est defectus numeri. Eius licet rusticitati hoc etenim iura precipiunt sit parcendum{+.} non tamen obiectum errorem ne tacendo huic consentire videar impurgatum censui{|}relinquendum. Quamobrem hoc opusculum edidi et quicquid de notarum alterationibus sentiam in eo posui. ut quom id perlegere**Word originally written with an ‘s’ in place of “-re”; erased and “-(re)” abbreviation sign written over 3rd ‘e’ by original scribe.** dignatus fueris me reprehen-<marg: fore (right) foot><newhand: 15th-/16th-century binder, hereafter B>k1</newhand></marg>[-75v-]sum inique precipias. et adversus calumniatorem{+.} pro veritate certando{-.} quod proprium est viri fortis{+.} tuearis et protegas:</prologue>\n\
<chapter> {blue}¶ <red>Quid sit alteratio. Capitulum. primum:</red>\n\
{4line}{blue}ALteratio est proprii valoris alicuius note duplicatio. Notam etenim alterari nihil aliud est. quam cum suo proprio valoris alterius similis{|}effici. Hinc circa notarum alterationem primo generaliter versando octo generales regulas tradere proposui:\n\
{blue}¶ <red>Prima generalis regularis:</red>\n\
{2line}{red}PRima generalis regula est quod ubicunque due note eiusdem speciei ternario numero subiecte inveniuntur sole{+.} ultima earum alteratur: {red}¶ Due autem note huiusmodi sole inveniri dicuntur quando non habent**Word written over erasure.** aliquam similem continuam aut sincopatam precedentem que cum illis numerari possit. Nanque si aliqua similis que cum illis numerari possit. continue vel per sincopam precedat. tunc omnes tres connumerabuntur{+.} et eo quod cessante causa cesset effectus{+.} cessante numeri imperfectione cessabit alteratio. ut patet in sequenti exemplo:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} _{mens: Ø7}PL5-9x3MG <lig>LF LG</lig> Ma LD <lig>BE BF</lig> LG Ba <lig>SG Sb</lig> Sc Bd Sc mb_.11 mG ma SG LD <lig><obl>BG BF <label>plum.</label></obl></lig> SG. ma Sb. mc md SG La MG |5-11___________ </example>\n\
{blue}¶ Dupliciter autem contingere**Final letter written over erasure.** potest quod due note ternario numero subiecte similem non habeant precedentem que cum illis numerari possit. primo [-76r-] quando realiter nulla precedit{+.} secundo quando aliqua precedit sed impletione ad alium locum reduci ostenditur{+.} vel ab illis puncto dividitur**‘t’ originally followed by a minim (? connecting directly to “ut”); minim erased and “-(ur)” abbreviation sign added by original scribe.** ut hic\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} <label>Exem</label> {solm: 0} {mens: Ø11}PL7-11x3 <lig><obl>Bg Be</obl></lig> Md Le {full}Bf <lig><obl>Bd Bc</obl></lig> {full}Ld BG. Sb. <lig>Sa Sb Bc</lig>. Sd mc ma mb Lc <lig><obl>Bb <label>  plum</label> BG</obl> Ba</lig> MG |4-11_ </example>\n\
{blue}¶ <red>Secunda generalis regula:</red>\n\
{2line}{blue}SEcunda generalis regula est. quod non refert si due note sole invente. quarum ultima venit alteranda sint continue aut sincopate{+.} quia dum in istis sicut in illis requiritur perfectio consequenter accidit**‘a’ written over erasure.** alteratio. sicut{-.} hic:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} <label>Exem</label> {solm: 0} {mens: Ø9}PL7-11x3 Md <lig>Le Lg</lig> Mf. Le Md. Lc Md LG <lig>Ba Bb</lig> Lc. Sd Bc. Sb <label>  plum.</label> Ba MG |5-12 [-] </example>\n\
{blue}¶ <red>Tertia**Originally written “Tercia”; ‘c’ altered to ‘t’ by corrector.** generalis regula:</red>\n\
{2line}{red}TErcia generalis regula est quod omnis nota que alteratur. necessario ante suam maiorem propinquam alteratur. ut longa ante maximam. brevis ante longam. semibrevis ante brevem. et minima ante semibrevem. Cuius ratio duplex est prima quoniam loco note alterande maior propinqua poni non potest. eo quod similis ante similem non imperficitur. unde que per alterationem valet <marg: fore (right) foot><newhand: B>k2</newhand></marg> [-76v-] tantummodo duas necesse valeret tres. ad quod evitandum secunda prime similis est alterabilis. Secunda ratio est. quoniam due note minores eiusdem speciei ante maiorem remotam aut remotiorem aut remotissimam posite{+.} ut due breves ante maximam due semibreves ante longam{+.} due minime ante brevem aut due semibreves ante maximam. due minime ante longam{+.} aut due minime ante maximam: possunt eam imperficere{+.} et sic absque alteratione numerus est in perfectione. ut hic patet:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exemplum</label> {solm: 0} _{mens: Ø5}PL5-9 -MD <lig>LE LD</lig> MG. BF <lig>LG La</lig> <lig>Bb Bc</lig> Ld Bc <lig><obl>Sb SG</obl> Ba</lig> LG LD**Three short red vertical ticks crossing 4th staff line, aligned with right edge of preceding ligature, left edge of longa G, and right edge of longa D.** <lig>BE BF</lig> SG ma mb <label>tertie</label> Sc Ld. <lig><obl>Bb BG</obl> Ma</lig> c ____ {staf: 5} _{clef: C10} <label>regule</label> {solm: 0} -LD. <lig>SG SF LE</lig> BF. mD mE BF <lig>Sa Sb</lig> Sc <lig><obl>Sd Sb</obl></lig> Ma Lb. ma mb Lc <lig><label>generalis</label> BG Ba Bb</lig>. mG ma -MD <lig>LG Lb</lig> La MG |4-10____ </example>\n\
{blue}¶ <red>Quarta generalis regula:</red>\n\
{2line}{red}Quarta generalis regula est quod licet duas notas minores ante maiorem propinquam solas inventas alia maior remota vel remotior vel remotissima ab illis duabus imperfectibilis precedat{+.} tamen eo quod imperfectio tanquam odiosa magis quam alteratio sit evitanda. non hec ab illis imperficietur. immo**Written “īmo”; tittle over ‘i’ very faint (poor ink adhesion).** ultima illarum alterabitur. nisi puncto ab{_}invicem vel ambe ab ipsa maiore propinqua**Word written over erasure.** [-77r-] dividantur. ut patet in sequenti exemplo:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} <label>Exem</label> {solm: 0} _{mens: Ø5}PL5-9x3 MG <lig>Bb Bc La</lig> Md <lig>Se Sf <obl>Bg Bd</obl></lig> Mf md me <lig><obl>Sd Sc</obl></lig> Ld Sb. SG Ba mF mG_.7 <lig>Sa Sb <label>plum</label> Bc</lig> Ld <lig>Bb Bc BG La</lig> LG |4-11 </example>\n\
{blue}¶ <red>Quinta generalis regula:</red>\n\
{2line}{blue}Quinta generalis regula est quod omnis nota veniens alteranda quo ad formam necessario est integra. Eius vero socia per partes potest esse divisa ut hic\n\
<example: {full measure + left ½-column, parallel to following heading and first 6 lines of following paragraph}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Ex</label> {solm: 0} {mens: Ø11}PL7-11 Md <lig><obl>Bc Bb</obl></lig> SG mF mG ma <lig><obl>SF SD</obl></lig> LE MD <lig>LG LE</lig> BF. <lig><obl>SG SF</obl></lig> SG Ba <label>  em</label> LG c {staf: 5} {clef: C10} {solm: 0} Bc. ma mb Sc <label>plum.</label> Bd SG mE_.7 <void>sD sE</void> mF SG. mb Sa LG | </example>\n\
<red>- Sexta generalis regula</red>\n\
{2line}{red}SExta generalis regula est quod licet pause loco notarum sociarum alterandarum aut partium suarum{-.} habeant vim inducendi alterationem nulla tamen alterari potest ut hic patet: <marg: fore (right) foot><newhand: B>k3</newhand></marg>\n\
<example: {full measure}, {mensural: void}, {staf: 4, red}> _<ll: -1, blind> _{clef: C10} <label>Exem</label>**Staff originally ruled with 5 lines; lowest line apparently scraped out, leaving only traces of red ink.** {solm: 0} {mens: Ø7}PL3-7x3 PL5-9 Lb ME LF PB7 BD LE MB. BC_.5 PS3 SC BD LE SF Pm7 mF SG <lig>Ba Bb</lig> <lig>LE LF</lig> LE </ll>cb ___ [-77v-] {staf: 5} _{clef: C10} {solm: 0} {mens: C11}PL7-11x3 Ld PL7-11 MG La BF PB7 LG {mens: O5} MD BE SE PS5 BF <lig>SG Sa</lig> Sb <lig>La LG</lig> {mens: Ø5} <lig>BD <label>plum.</label> BG</lig> <lig>SF Sa</lig> ma Pm9 Sb <lig>Bc Bd</lig> Sb. SG Ba LG |5-11___ </example>\n\
{red}¶ Preterea talis ante pausas perfectas fit alteratio qualis ante notas quibus sunt appropriate. hinc fit ut ante pausam longe in modo minori perfecto alteretur brevis{+.} ante pausam brevis in tempore perfecto semibrevis{+.} et ante pausam semibrevis in # maiori prolatione minima. ut hic patet:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} {mens: Ø7}PL7-11x3 <lig>LG La</lig> Lb <lig>Bc Bd</lig> PL7-11x2 LG BF BG <lig><obl>SE SD</obl></lig> PB5 LF <lig>SG Sa</lig> mb mG PS7 <lig><obl>Sa SF <label> plum.</label></obl></lig> SG Ba MG |6-12 </example>\n\
{blue}¶ <red>Septima generalis regula:</red>\n\
{2line}{red}SEptima generalis regula est quod ligatura non facit alterationem unde si tres note minores inveniantur ante maiorem propinquam quarum due ultime sunt colligate ac etiam ipsi maiori colligate. licet aliqua maior propinqua vel remota vel remotior eas precedat que a prima earum posset imperfici{+.} tamen eo quod imperfectionem atque alterationem quantum possumus propter improprietatem utriusque fugere debemus{+.} ultima non alteratur. immo cum duabus primis numeratur. nisi puncto <expunction><strikethrough>puncto</strikethrough></expunction> a duabus ultimis prima dividatur. ut patet insequenti exemplo:\n\
[-78r-] <example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} _{mens: O7}PL5-9x3 MG LF <lig>LG La</lig> <lig>MG Md</lig> Bb <lig>BG Ba LD</lig> LG ME SF <lig>SG Sa</lig> <lig>Bb Bc</lig> Bd <label>  plum.</label> Sc .9 <lig><obl>Sb SG</obl> Ba</lig> LG |4-11 </example>\n\
{red}¶ Talis attamen colligationis modus nisi fiat propter dicta supposita plurimum est fugiendus{+:} multo nempe convenientius aut nulle talium trium notarum aut omnes aut prima et secunda colligantur. ut hic patet\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} _{mens: O7}PL5-9x3 MG LF LG La <lig>MG Md</lig> <lig><obl>Bb BG</obl> Ba</lig> LD LG ME**Note head originally written in square proportion as if a breve; right-hand vertical stroke erased and note head extended to right.** <lig>SF SG</lig> Sa Bb <label>  plum.</label> Bc Bd Sc .9 <lig><obl>Sb SG</obl> Ba</lig> LG |4-11__ </example>\n\
{blue}¶ <red>Octava generalis regula:</red>\n\
{2line}{blue}OCtava generalis regula est. quod omnis nota ternario numero subiecta est alterabilis. unde quom longa in modo maiori perfecto. brevis in modo minori perfecto. semibrevis in tempore perfecto{+.} et minima in prolatione maiori{+.} numero ternario sint subiecte. in ipsis quantitatibus veniunt alterande. De quarum{_}qui{_}dem alterationibus. ut clarius intelligatur. nunc particulariter tractare**Originally begun “trac-” at line end; ‘c’ erased and hyphen written over by original scribe.** proposuimus:</chapter>\n\
<chapter>{blue}¶ <red>De alteratione longe. Capitulum. secundum:</red>\n\
{4line}{gold}SI due longe sole in modo maiori perfecto ante maximam inveniantur ultima illarum alteratur. ut patet in sequenti exemplo: <marg: fore (right) foot><newhand: B>k4</newhand></marg>\n\
[-78v-] <example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} _{mens: O5}PL5-9x3 MD <lig>LG La</lig> MG. La Mb. Lc Md <lig>LG La Lb</lig> <lig>Lc <label>plum</label> La</lig> MG**Large semicircular dot (SE half) between final note and barline; probably dirt or offset.** |5-12 [-] </example>\n\
{blue}¶ <red>De alteratione brevis:</red>\n\
{2line}{red}SI due breves sole in modo minori perfecto{-.} ante longam{-.} aut eius pausam inveniantur. ultima illarum alteratur. ut patet insequenti exemplo:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} {mens: C7}PL5-9x2 <lig><obl>BG BE</obl></lig> LD <lig>BE BF</lig> PL5-9 LG Ba .7 <lig><obl>BF BE</obl></lig> BD <lig>BF BG</lig> <lig>La Bd</lig>. <lig>BG Ba BF BG Ba</lig> PL7-11 Ld <label>plum.</label> <lig>BG <obl>Bb Ba</obl></lig>**Two dots like a colon in top space of staff above 2nd note of ligature; probably offset.** LG |5-12 </example>\n\
{blue}¶ <red>De alteratione semibrevis:</red>\n\
{2line}{blue}SI due semibreves sole in tempore perfecto ante brevem aut eius pausam inveniantur. ultima illarum alteratur. ut patet in sequenti exemplo:\n\
<example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} {mens: Ø11}PL9-11 Bd <lig><obl>Sb Sa</obl></lig> BG <lig>Sa Sb</lig> PB9 BG. Sa BF. SE <lig>BD Ba</lig> <lig>SG Sa</lig> Sb <lig><obl>Sc Sb</obl></lig> Ba <lig>SG Sa</lig> Sb <lig><label>plum.</label> Sc Sd</lig> PB11 <lig>BG Ba</lig> MG </example>\n\
{blue}¶ <red>De alteratione**Originally written “alteratio”; ‘e’ crowded in and tittle over ‘o’ added by corrector.**{|}minime</red>\n\
{2line}{red}SI due minime sole in maiori prolatione ante semibrevem{-.} aut eius pausam inveniantur: ultima illarum alteratur ut hic patet:\n\
[-79r-] <example: {full measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>Exem</label> {solm: 0} _{mens: Ç5}PL5-7 SD mE mF <lig>SG Sa</lig> mb mc PS9 Sd mc .9 ma mb mc md mG Sa mD mF mE mD mF PS5 SG <lig>Sa Sb</lig> Sc md . mb <label> plum</label> mG Sa mc . mb Sa LG |5-12 [-] </example></chapter>\n\
<chapter>{blue}¶ <red>Operis conclusio. Capitulum tercium:</red>\n\
{4line}{gold}ITaque sufficienter de ipsis notarum alterationibus tam generaliter quam particulariter tractatum mihi profecto visum est. sitamen aliqua necessaria circa eas pretermiserim{+.} aut falsa preceperim: calumniatorem precor{-.} ut illa sub iungere: aut ista corrigere dignetur. Nanque tunc reprehensione dignum menie existimabo ac eum preceptorem auctentissimum hic et ubique predicabo:</chapter>\n\
<explicit>{blue}¶ <red>Scriptum de imperfectione notarum musicalium explicit:</red>**Explicit begins in last ⅓ of last line of Conclusio; continues “Nunc de punctis musicalibus: Prologus incipit:”**</explicit></treatise>';
texts.dealterationenotarum.Br1 = 'De alteratione notarum\n\
Data entry: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 2015 05 29\n\
Base file: De alteratione notarum (BU).txt\n\
Source: B-Br II 4147 Mus., fols. 44va-47ra\n\
Script: Hybrid bastarda, 2 columns per page\n\
Running heads: [none]\n\
[-IIr-] <index>\n\
{large}{red}T{redline}Abula tractatus alterationum incipit	45\n\
{redline}Quid sit alteratio	{redline}Ca[-]1\n\
{redline}De alteratione longe	{redline}Ca[-]2\n\
{redline}Operis conclusio	{redline}Ca[-]3\n\
</index>\n\
[-44va-] <treatise> {blue}¶ <red>Tractatus alterationum editus a magistro iohanne tinctoris in legibus licentiato regis que magne sicilie capellano</red>\n\
<prologue> [-][-] {blue}¶ <red>Prologus:~</red>\n\
<6line>[S]</6line>{redline}Anctissimo legum interpreti, suavissimo que musarum cultori, {redline}Guillelmo guinandi prothocapellano serenissimi ducis mediolani, {redline}Johannes tinctoris inter legum ac artium mathematicarum studiosos minimus honorem perpetuum que decus Nuper egregie vir) meas usque ad aures rumor subvolavit quendam cantorem tuo subiectum imperio, me palam asseruisse, circa quandam alterationem musicam errasse, eo quod (quom in manibus suis habuisset officium nostrum ia olim super Nos amis editum) in ipso sub tempore perfecto inter duas breves, duas semibreves quarum ultima non alteratur hoc in modo repperisset\n\
<example: {left ½-column, parallel to 1 blank line and first 3 lines of following paragraph}, {mensural: void}, {staf: 3, red}> _{clef: F6} <label>{red}¶ {redline}Exemplum</label> {solm: 0} {mens: O7} PS7_PS7 Ba mG mF SE BD {redline}|| </example>\n\
{blue}¶ In quo se ad modum esse rusticum ostendit non advertens alterationem aliquam non debere fieri ubi nullus est defectus numeri.**Abbreviation probably to be read as “nui^r^”, not “mu^r^” (muneri).** {redline}Cuius licet rusticitati hoc etenim iura precipiunt, sit parcendum non tamen obiectum errorem ne tacendo huic, consentire videar) impurgatum s**This letter may have been struck through vertically; it suggests that the scribe pronounced the following word in the French fashion rather than the Italian.** censui relinquendum {redline}Quamobrem hoc opusculum edidi et quicquid de notarum alterationibus sentiam in eo posui. Ut [-44vb-] quom id perlegere dignatus fueris, me reprehensum inique precipias, et adversus calumniatorem pro veritate certando, quod proprium est viri fortis, tuearis et protegas</prologue>\n\
<chapter> {blue}¶ <red>Quid sit alteratio capitulum. 1^m.</red>\n\
{2line}{red}Alteratio est proprii valoris alicuius note duplicatio Notam etenim alterari nichil aliud est, quam cum suo proprio valoris alterius similis effici Hinc circa notarum alterationem primo generaliter versando octo generales regulas tradere proposui\n\
{blue}¶ <red>Prima generalis regula</red>\n\
{2line}{blue}PRima generalis regula est quod ubicumque due note eiusdem speciei ternario numero subiecte inveniuntur sole, ultima earum alteratur: {red}¶ {redline}Due autem note huiusmodi sole inveniri dicuntur quando non habent aliquam similem continuam aut sincopatam precedentem que cum illis numerari possit {redline}Namque si aliqua similis que cum illis numerari possit continue vel per sincopam precedat, tunc omnes tres connumerabuntur et eo quod cessante causa cesset effectus cessante numeri imperfectione, cessabit alteratio ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 4, red}> _{clef: C10} {solm: 0} _{mens: Ø7}PL5-9x3 MG <label>{red}¶ {redline}Exem**3rd letter apparently begun as ‘x‘, immediately corrected to ‘e’.**</label> <lig>LF LG</lig> Ma LD <lig>BE BF</lig> LG Ba <lig>SG Sb</lig> Sc Bd Sc mb _c ______ {staf: 3} _{clef: C8} {solm: 0} mG ma SG LD**There is not even a blind-ruled leger line for this note.** <lig><obl>BG BF</obl></lig> SG. ma Sb<label: 4>plum</label>. mc md SG La MG <redline>||0-10 </example>\n\
[-45ra-] {blue}¶ Dupliciter autem contingere potest quod due note ternario numero subiecte similem non habeant precedentem que cum illis numerari possit {redline}Primo quando realiter nulla precedit Secundo quando aliqua precedit sed impletione ad alium locum reduci ostenditur vel ab illis puncto dividitur ut hic\n\
<example: {column measure + left ⅗-column, parallel to 1 blank line, following heading in 3 lines, and 1 blank line}, {mensural: void}, {staf: 5, red}> _{clef: C8} {solm: 0} _{mens: Ø11}PL7-11x3 <lig><obl>Bg Be</obl></lig> Md <label>{red}¶ {redline}Exem</label> Le {full}Bf <lig><obl>Bd Bc</obl></lig> {full}Ld BG. Sb. <lig>Sa Sb Bc</lig>. c _____ {staf: 5} _{clef: C10} {solm: 0} Sd mc ma mb <label>  plum</label> Lc <lig><obl>Bb BG</obl> Ba</lig> MG {redline}|| </example>\n\
{blue}¶ <red>Secunda generalis regula:~</red>\n\
{2line}{red}S{redline}Ecunda generalis regula est quod non refert si due note sole invente quarum ultima venit alteranda sint continue aut sincopate (quia dum in istis sicut in illis requiritur perfectio consequenter accidit alteratio sicut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} {solm: 0} {mens: Ø9}PL7-11x3 <label>  {red}¶ {redline}Exem</label> Md <lig>Le Lg</lig> Mf. Le Md. Lc Md c ____ {staf: 5} _{clef: C10} {solm: 0} LG <lig>Ba Bb</lig> Lc. <label>plum</label> Sd Bc. Sb Ba MG {redline}|| [-] </example>\n\
[-45rb-] {blue}¶ <red>Tercia generalis regula:~</red>\n\
{2line}{blue}T{redline}Ercia generalis regula est, quod omnis nota que alteratur, necessario ante suam maiorem propinquam alteratur ut longa ante maximam brevis ante longam semibrevis ante brevem, et minima ante semibrevem {redline}Cuius ratio duplex est {redline}Prima quoniam loco note alterande maior propinqua poni non potest eo quod similis ante similem non imperficitur Unde que per alterationem valet tantummodo duas necesse valeret tres, ad quod evitandum secunda prime similis est alterabilis {redline}Secunda ratio est, quoniam due note minores eiusdem speciei ante maiorem remotam aut remotiorem aut remotissimam posite, ut due breves ante maximam due semibreves ante longam due minime ante brevem aut due semibreves ante maximam due minime ante longam aut due minime ante maximam possunt eam imperficere, et sic absque alteratione numerus est in**Word originally written as “im(perfectione)”; 1st minim struck through and dot placed above 2nd by original scribe to turn ‘m’ into “in”.** perfectione ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} _{mens: Ø5}PL5-9 MD <lig><label> {red}¶ {redline}Ex</label> LE LD</lig> MG. BF <lig>LG La</lig> <lig>Bb Bc</lig> Ld c ___ {staf: 5} _{clef: C10} {solm: 0} Bc <lig><obl>Sb SG</obl> Ba</lig> LG LD <lig>BE BF</lig> SG ma <label>em</label> mb Sc Ld. [-] c __ [-45va-] {staf: 5} _{clef: C12} {solm: 0} <lig><label>{red}¶ {redline}Ex</label><obl>Bb BG</obl> Ma</lig> LD. <lig>SG SF LE</lig> BF. mD mE BF <label>  em</label> <lig>Sa Sb</lig> Sc <lig><obl>Sd Sb</obl></lig> c __ {staf: 5} _{clef: C12} {solm: 0} Ma Lb. ma mb Lc <label>  plum</label> <lig>BG Ba Bb</lig>. mG ma MD <lig>LG Lb</lig> La MG {redline}||__ </example>\n\
{blue}¶ <red>Quarta generalis regula</red>\n\
{2line}{red}Quarta generalis regula est quod licet duas notas minores ante maiorem propinquam solas inventas alia maior remota vel remotior vel remotissima ab illis duabus imperfectibilis precedat tamen eo quod imperfectio tamquam odiosa magis quam alteratio sit evitanda non hec ab illis imperficietur immo ultima illarum alterabitur nisi puncto abinvicem, vel ambe ab ipsa maiore propinqua dividantur ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C8} {solm: 0} _{mens: Ø5}PL5-9x3 MG <label>{red}¶ {redline}Ex</label> <lig>Bb Bc La</lig> Md <lig><label>em</label> Se Sf <obl>Bg Bd</obl></lig> Mf md me <lig><obl>Sd Sc</obl></lig> _c ______ {staf: 5} _{clef: C10} {solm: 0} Ld Sb. SG Ba mF mG.9 <lig><label: 4>plum</label> Sa Sb Bc</lig> Ld <lig>Bb Bc BG La</lig> LG {redline}|| </example>\n\
{blue}¶ <red>Quinta generalis regula</red>\n\
{2line}{blue}Quinta generalis regula est quod omnis nota veniens alteranda, quo ad formam necessario est [-45vb-] integra Eius vero socia perpartes potest esse divisa ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} {mens: Ø11}<label>{red}¶{redline}Ex</label>PL7-11 Md <lig><obl>Bc Ba</obl></lig> SG mF <label>em</label> mG ma <lig><obl>SF SD</obl></lig> LE MD <lig>LG LE</lig> BF. c ____ {staf: 5} _{clef: C10} {solm: 0} <lig>SG SF</lig> SG Ba LG Bc. ma <label> plum</label> mb Sc Bd SG mE. <void>sD sE</void> mF SG. mb Sa LG {redline}||3-12 </example>\n\
{blue}¶ <red>Sexta generalis regula</red>\n\
{2line}{red}S{redline}Exta generalis regula est quod licet pause (loco notarum sociarum alterandarum aut parcium suarum habeant vim inducendi alterationem nulla tamen alterari potest ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} {mens: Ø7}PL5-9x3_PL7-11 Ld MG <label> {red}¶ {redline}Ex</label> La PB7 BF LG MD BE PS5 SE BF c ___ {staf: 5} _{clef: C10} {solm: 0} LG Sa Pm9 ma Sb <lig>Bc Bd</lig> <lig>LG <label>em</label> La</lig> LG {mens: C11}PL7-11x3 Ld PL7-11 MG La BF PB7 c ___ {staf: 5} _{clef: C12} {solm: 0} LG {mens: O7} MD BE SE <label> plum</label> PS7 BF <lig>SG Sa</lig> Sb <lig>La LG</lig> c ___ [-46ra-] {staf: 5} _{clef: C12} {solm: 0} {mens: Ø7} <lig>BD BF</lig> <lig>SG Sa</lig> ma <label>plum</label> Pm11 Sb <lig>Bc Bd</lig> Sb. SG Ba LG {redline}||_ </example>\n\
{red}¶ {redline}Preterea talis ante pausas perfectas fit alteratio qualis ante notas quibus sunt appropriate hinc fit ut ante pausam longe in modo minori perfecto alteretur brevis {redline}Ante pausam brevis in tempore perfecto semibrevis et ante pausam semibrevis in maiori prolatione minima ut hic patet\n\
<example: {column measure + left ½-column, parallel to 2 blank lines and following heading in 3 lines}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} _{mens: Ø7}PL7-11x3 <lig>LG La</lig> Lb <label>  {redline}Exem</label> <lig>Bc Bd</lig> PL7-11x2 LG BF BG <lig><obl>SE SD</obl></lig> PB5 LF c ___ {staf: 5} _{clef: C10} {solm: 0} <lig>SG Sa</lig> mb mG PS7 <lig><label> plum</label> <obl>Sa SF</obl></lig> SG Ba MG {redline}||2-10__ </example>\n\
{blue}¶ <red>Septima generalis regula:~</red>\n\
{2line}{blue}S{redline}Eptima generalis regula est, quod ligatura non facit alterationem Unde si tres note minores inveniantur, ante maiorem propinquam quarum due ultime sunt colligate ac etiam ipsi maiori colligate licet aliqua maior propinqua vel remota vel remotior eas precedat que a prima earum posset imperfici tamen eo quod imperfectionem atque alterationem quantum possumus propter improprietatem utriusque fugere debemus [-46rb-] ultima non alteratur immo cum duabus primis numeratur nisi puncto, a duabus ultimis prima dividatur. ut hic patet\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} _{mens: O7}PL5-9x3 MG <label>{red}¶ {redline}Ex</label> LF <lig>LG La</lig> <lig>MG Md</lig> Bb <lig><label>em</label> BG Ba LD</lig> LG c ____ {staf: 5} _{clef: C10} {solm: 0} ME SF <lig>SG Sa</lig> <lig><label> plum</label> Bb Bc</lig> Bd Sc .9 <lig><obl>Sb SG</obl> Ba</lig> LG {redline}||3-12__ </example>\n\
{blue}¶ {redline}Talis attamen colligationis modus nisi fiat propter dicta supposita, plurimum est fugiendus multo nempe convenientius aut nulle talium trium notarum aut omnes aut prima et secunda colligantur ut hic <red>:~</red>\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} {mens: O7}PL5-9x3 MG <label>  {red}¶ {redline}Exem</label> LF LG La <lig>MG Md</lig> <lig><obl>Bb BG</obl> Ba</lig> c ____ {staf: 5} _{clef: C10} {solm: 0} LD LG ME <lig>SF SG</lig> Sa <label>plum</label> Bb Bc Bd Sc. <lig><obl>Sb SG</obl> Ba</lig> LG {redline}||3-12___ </example>\n\
{blue}¶ <red>Octava generalis regula:</red>\n\
{2line}{red}Octava generalis regula est quod omnis nota ternario numero subiecta est alterabilis unde (quom longa in modo maiori perfecto [-46va-] brevis in modo minori imperfecto semibrevis, in tempore perfecto et minima in prolatione maiori numero ternario sint subiecte in ipsis quantitatibus veniunt alterande De quarumquidem alterationibus ut clarius intelligatur nunc particulariter tractare proposuimus</chapter>\n\
<chapter>{blue}¶ <red>De alteratione longe capitulum 2^m.</red>\n\
{2line}{blue}Si due longe sole, in modo maiori perfecto ante maximam inveniantur ultima illarum alteratur ut hic patet\n\
<example: {column measure + left ⅗-column, parallel to 1 blank line, following heading in 2 lines, and 1 blank line}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{red}¶ {redline}Ex</label> {solm: 0} _{mens: O5}PL5-9x3 MD <lig>LG La</lig> MG. La Mb<label>em</label>. Lc Md c ___ {staf: 5} _{clef: C10} {solm: 0} <lig>LG La Lb <label: 4>plum</label></lig> <lig>Lc La</lig> MG <redline>|| ||</redline>__ </example>\n\
{blue}¶ <red>De alteratione brevis</red>\n\
{2line}{red}Si due breves sole in modo minori perfecto ante longam aut eius pausam inveniantur ultima illarum alteratur ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} {mens: C7}<label>{red}¶ {redline}Ex</label>PL5-9x2 <lig><obl>BG BE</obl></lig> LD <lig>BE BF</lig> PL5-9 LG Ba .7 <lig><label>em</label> <obl>BF BE</obl></lig> BD <lig>BF BG</lig> c ___ {staf: 5} _{clef: C10} {solm: 0} <lig>La Bd</lig>. <lig>BG Ba BF <label>plum</label> BG Ba</lig> PL7-11 Ld <lig>BG <obl>Bb Ba</obl></lig> LG {redline}||2-12 </example>\n\
[-46vb-] {blue}¶ <red>De alteratione semibrevis</red>\n\
{2line}{blue}SI due semibreves sole, in tempore perfecto ante brevem aut eius pausam inveniantur ultima illarum alteratur ut hic\n\
<example: {column measure + left ⅔-column, parallel to 1 blank line and following heading in 3 lines}, {mensural: void}, {staf: 5, red}> _{clef: C10} <label>{red}¶ {redline}Ex</label> {solm: 0} {mens: Ø11}PL9-11 Bd <lig><obl>Sb Sa</obl></lig> BG <lig>Sa Sb</lig> PB9 BG. Sa BF. SE <lig>BD <label>em</label> Ba</lig> <lig>SG Sa</lig> Sb <lig><obl>Sc Sb</obl></lig> c _____ {staf: 5} _{clef: C10} {solm: 0} Ba <lig>SG <label> plum</label> Sa</lig> Sb <lig>Sc Sd</lig> PB11 <lig>BG Ba</lig> MG {redline}||__ </example>\n\
{blue}¶ <red>De alteratione minime</red>\n\
{2line}{red}Si due minime sole in maiori prolacione ante semibrevem aut eius pausam inveniantur ultima illarum alteratur ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, red}> _{clef: C10} {solm: 0} {mens: Ç5}PL5-7 <label>  {red}¶ {redline}Ex</label> SD mE mF <lig>SG Sa</lig> mb mc PS9 Sd mc .9 ma mb mc md mG <label>em</label> Sa c ___ {staf: 4} _{clef: C10} {solm: 0} mD mF mE mD mF PS5 SG <lig>Sa <label: 4>plum</label> Sb</lig> Sc md. mb mG Sa mc. mb Sa LG {redline}||_ </example></chapter>\n\
{2line}{blue}Itaque sufficienter de ipsis notarum alterationibus tam generaliter quam particulariter tractatum mihi profecto visum est {redline}Si tamen aliqua necessaria circa eas pretermiserim aut falsa preceperim, calumniatorem precor ut illa subiungere aut ista corrigere dignetur {redline}Namque [-47ra-] tunc reprehensione dignum meme existimabo ac eum preceptorem auctentissimum hic et {strikethrough}hubique predicabo <red>:~</red></chapter></treatise>';
texts.dealterationenotarum.G = 'De alteratione notarum\n\
Data entry: Jeffrey J. Dean\n\
Checked by:\n\
Date established: 2015 05 29\n\
Base file: De alteratione notarum (Br1).txt\n\
Source: B-Gu 70, fols. 168vb-171va (modern numeration)\n\
Script: Lettre bourguignonne, 2 columns per page\n\
Running heads: [none]\n\
[-168vb-] <treatise><incipit> {redline}Incipit tractatulus feliciter de alterationibus notarum.</incipit>\n\
[7 blank lines]\n\
[-169ra-] <incipit> [.]<red>De alterationibus notarum tractatulus feliciter incipit §</red></incipit>\n\
<chapter><3line>[A]</3line>**Cue letter ‘A’ has been written in the centre of the first line of the blank space in what looks like pencil and an 18th-/19th-century hand.**{redline}Lteratio est proprii valoris alicuius note duplicatio, {redline}Notam etenim alterari nihil aliud est, quam cum suo proprio valoris alterius similis effici, {redline}Hinc circa notarum alterationem primo generaliter versando, octo generales regulas trademus. [-]<red>§[-]§[-]§</red>\n\
<red>Prima regula alterationum.</red>\n\
<2line>[P]</2line>{redline}Rima generalis regula est quod ubicunque due note eiusdem speciei ternario numero subiecte inveniuntur sole. ultima earum alteratur {redline}Due autem note huiusmodi sole inveniri dicuntur, quando non habent aliquam similem. continuam aut sincopatam, precedentem, que cum illis possit numerari, {redline}Namque si aliqua similis, que cum illis numerari possit continue vel per sincopam precedat, tunc omnes tres connumerabuntur, et eo quod cessante causa cesset effectus, cessante numeri imperfectione cessabit alteratio.\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: Ø9}<label>  {red}¶ {redline}Ex</label>PL7-11x3 MG <lig>LF LG</lig> Ma -LD <lig>BE BF</lig> c ____ {staf: 5} _{clef: C10} {solm: 0} LG Ba <lig><label>  em-</label> SG Sb</lig> Sc Bd Sc mb_.11 mG ma SG -LD c ___ {staf: 5} _{clef: C10} {solm: 0} <lig><obl>BG BF</obl></lig> SG. ma <label>plum.</label> Sb. mc -md SG La MG <label>{red}§</label> ||3-10___ </example>\n\
[-169rb-] {redline}Dupliciter autem contingere potest quod due note ternario numero subiecte. similem non habeant precedentem, que cum illis, numerari possit. primo scilicet: quando realiter nulla precedit {redline}Secundo quando aliqua precedit sed impletione ad alium locum reduci ostenditur, vel ab illis puncto dividitur ut hic\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C8} {solm: 0} {mens: Ø9}PL7-11x3 <label>{red}¶ {redline}Ex-</label> <lig><obl>Bf Be</obl></lig> Md Le {full}Bf <label>em-</label> <lig><obl>Be Bc</obl></lig> c ___ {staf: 5} _{clef: C8} {solm: 0} {full}Ld BG. Sb. <lig><label> plum. {red}.</label> Sa Sb Bc</lig>. Sd mc ma mb Lc <label><red>§ .</red></label> <lig><obl>Bb BG</obl> Ba</lig> -LG |_____ </example>\n\
<red>Secunda regula generalis alterationum.[.]§</red>\n\
<large>[S]</large>{redline}Ecunda regula generalis est quod non refert si due note sole invente, quarum ultima venit alteranda sint continue, aut sincopate, quia dum in istis sicut in illis requiritur perfectio, consequenter accidit alteratio. ut in exemplo subsequenti. {red}§ <marg: foot, centred on vertical rule for fore (right) margin><newhand: 16th-century binder, hereafter B>[illegible through severe trimming]</newhand></marg>\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C8} {solm: 0} {mens: Ø9}PL7-11x3 <label>{red}¶ {redline}Ex-</label> Md <lig>Le Lg</lig>. Mf. Le c _ {staf: 5} _{clef: C8} {solm: 0} Md. Lc Md <label>em- <red>. § .</red></label> -LG <lig>Ba Bb</lig> Lc. c ____ [-169va-] {staf: 5} _{clef: C8} {solm: 0} Sd Bc. Sb <label>  plum.</label> Ba -LG || [-][-]<label>{red}§</label>[-][-]<label><red>##</red></label>[-] </example>\n\
[.]<red>Tercia regula generalis</red>\n\
<2line>[T]</2line>{redline}Ercia regula generalis est quod omnis nota que alteratur necessario ante suam maiorem propinquam alteratur ut longa ante maximam, {redline}Brevis ante longam, semibrevis ante brevem, et minima ante semibrevem, {redline}Cuius ratio duplex est {redline}Prima quidem quoniam loco note alterande maior propinqua poni non potest eo quod similis ante similem imperfici non possit {redline}Unde que per alterationem valet tantum duas necesse valeret tres. {redline}Ad quod evitandum, secunda prime similis est alterabilis. - {redline}2^a est ratio quoniam due note minores eiusdem speciei ante maiorem remotam aut remotiorem aut remotissimam posite, ut due breves ante maximam vel due semibreves ante longam, vel due minime ante brevem, vel due semibreves ante maximam, vel due minime ante longam, vel due minime ante maximam possunt eam imperficere. {redline}Et sic absque alteratione numerus est in perfectione ut hic. in exemplo subsequenti.[.]{red}§\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} PL5-9{mens: Ø7} <label>{red}¶ {redline}Exemplum.   {red}§</label> -MD <lig>LE LD</lig> MG. BF <lig>LG La</lig> c ____ [-169vb-] {staf: 5} _{clef: C10} {solm: 0} <lig>Bb Bc</lig> Ld Bc <lig><obl>Sb SG</obl> <label>{redline}Ex-</label> Ba</lig> LG -LD <lig>BE BF</lig> c _ {staf: 5} _{clef: C10} {solm: 0} SG ma mb Sc Ld. <lig><obl>Bb BG<label>em-</label></obl> Ma</lig> c __ {staf: 5} _{clef: C10} {solm: 0} -LD. <lig>SG SF LE</lig> BF. mD mE BF <label> plum.   {red}§</label> <lig>Sa Sb</lig> Sc <lig><obl>Sd Sb</obl></lig> c ___ {staf: 5} _{clef: C10} {solm: 0} Ma <label>{red}¶ {redline}Ex</label> Lb. ma mb Lc <label>   em-</label> <lig>BG Ba Bb</lig>. mG ma c ___ {staf: 5} _{clef: C10} {solm: 0} -MD <label>   plum.</label> <lig>LG Lb</lig> La MG <label>{red}§</label> || [-] <label>{red}§</label> </example>\n\
<red>Quarta regula generalis §</red>\n\
<2line>[Q]</2line>{redline}Uarta regula generalis est quod licet duas notas minores ante minorem propinquam solas inventas: alia maior remota, vel remotior, vel remotissima, ab illis duabus imperfectibilis, tamen eo quod imperfectio tanquam odiosa magis quam alteratio sit evitanda, non hec ab illis imperficietur ymmo ultima illarum alterabitur nisi puncto abinvicem vel ambe ab ipsa maiore propinqua dividantur ut hic in exemplo sequenti.[.]<red>§[.]-[.]§</red>\n\
[-170ra-] <example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C8} {solm: 0} {mens: Ø7}<label>  {red}¶ {redline}Ex-</label>PL5-9x3 -MG <lig>Bb Bc La</lig> Md c __ {staf: 5} _{clef: C8} {solm: 0} <lig>Se Sf <obl>Bg Be</obl></lig> Mf <label>em-</label> md me <lig><obl>Sd Sc</obl></lig> Ld Sb. c __ {staf: 5} _{clef: C8} {solm: 0} SG Ba mF mG_.9 <label>plum.  <red>-  §  -</red></label> <lig> Sa Sb Bc</lig> Ld <lig>Bb Bc BG La</lig> -LG || </example>\n\
<red>Quinta regula generalis.</red>\n\
<2line>[Q]</2line>{redline}Uinta regula generalis est quod omnis nota veniens alteranda quo ad formam, necessario est integra. {redline}Eius vero - socia per partes potest esse divisa. ut in exemplo sequenti. {red}§\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: Ø11}<label>{red}¶{redline}Ex-</label>PL7-11 Md <lig><obl>Bc Bb</obl></lig> SG mF mG ma c ___ {staf: 5} _{clef: C10} {solm: 0} <lig><obl>SF SD</obl></lig> -LE -MD <label>em-</label> <lig>LG LF</lig> BF. <lig><obl>SG SF</obl></lig> SG Ba c ______ {staf: 5} _{clef: C10} {solm: 0} LG Bc. ma mb <label>plum.  <red>- -   §</red></label> Sc Bd SG mE. <void>sD mE</void> mF SG. mb Sa LG ||5-10_____ </example>\n\
[-170rb-] <red>Sexta regula generalis. § .</red>\n\
<2line>[S]</2line>{redline}Exta regula generalis est: quod licet pause loco notarum sociarum alterandarum aut partium suarum habeant vim reducendi alterationem, nulla tamen alterari potest ut hic{red}.\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> {clef: C10} {solm: 0} {mens: Ø7}<label> {red}¶ {redline}Ex-</label>PL5-9x3_PL7-11 Ld MG La PB7 BF LG c ___ {staf: 5} _{clef: C10} {solm: 0} -MD. <label>em-</label> BE PS5 SE BF LG Sa Pm9 ma Sb c __ {staf: 5} _{clef: C10} {solm: 0} <lig>Bc Bd</lig> <lig><label>plum.   <red>. §   §</red></label> LG La</lig> LG Ld ||_{redline}| [-][-][-] {staf: 5} _{clef: C10} {solm: 0} PL7-11x3 <label> {red}¶ {redline}Ex-</label> Ld PL7-11 MG La BF PB7 LG c ___ {staf: 5} _{clef: C10} {solm: 0} {mens: O7} -MD <label>  em-</label> BE SE PS5 BF <lig>SG Sa</lig> Sb <lig>La LG</lig> c ___ {staf: 5} _{clef: C10} {solm: 0} {mens: Ø5} <lig>BD BF</lig> <lig><label>plum.</label> SG Sa</lig> ma Pm9 Sb <lig>Bc Bd</lig> Sb<label>{red}§</label>. mG Ba LG<label>{red}.</label> ||4-10___ </example>\n\
[-170va-] {red}¶{redline}Preterea talis ante pausas perfectas fit alteratio: qualis ante notas quibus sunt appropriate. Hinc est ut ante pausam longe, in modo minori perfecto alteretur brevis, ante pausam brevis in tempore perfecto semibrevis, et ante pausam semibrevis in prolatione maiori minima. ut patet hic. &c. {red}§\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: Ø7}PL5-9x2 <lig><label>{red}¶ {redline}Ex-</label> LG La</lig> Lb <lig>Bc Bd</lig> PL7-11x2 LG BF <label>   {red}§</label> BG c __ {staf: 5} _{clef: C10} {solm: 0} <lig><obl>SE <label> em</label> SD</obl></lig> PB5 LF <lig>SG Sa</lig> mb mG <label> plum.</label> PS7 <lig><obl>Sa SF</obl></lig> SG Ba <label>  {red}§</label> LG || </example>\n\
<red>Septima regula generalis-</red>\n\
<2line>[S]</2line>{redline}Eptima regula generalis est quod ligatura non facit alterationem. {redline}Unde si tres note, minores inveniantur ante maiorem propinquam. quarum due ultime sunt colligate, ac etiam ipsi maiori colligate, licet aliqua maior propinqua, vel remota vel remotior eas precedat que a prima earum posset imperfici. tamen eo quod imperfectionem atque alterationem quantum possumus. propter improprietatem veriusque figere fugere debemus ultima non alteratur ymmo cum duabus primis numeratur, nisi puncto a duabus ultimis prima dividatur ut patet in exemplo subsequenti.[-]{red}§\n\
[2 blank lines]\n\
[-170vb-] <example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: O9}PL5-9x3 <label>{red}¶ {redline}Ex-</label> MG LF <lig>LG La</lig> <lig>MG Md</lig> c ___ {staf: 5} _{clef: C10} {solm: 0} Bb <lig>BG Ba LD</lig> LG <label>em-</label> -ME SF <lig>SG Sa</lig> <lig>Bb Bc</lig> c ___ {staf: 5} _{clef: C10} {solm: 0} Bd Sc . <lig><label> plum.  <red>.   §   .</red></label> <obl>Sb SG</obl> Ba</lig> -MG ||_{redline}| [-][-] </example>\n\
[.] {redline}Talis tamen colligationis modus nisifiat propter dicta supposita, plurimum est fugiendus. {redline}Multo nempe convenientius aut nulle talium trium notarum aut omnes, aut prima aut 2^a colligantur ut hic.[.]{red}§\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> {clef: C10} {solm: 0} {mens: O9}<label>{red}¶ {redline}Ex-</label>PL5-9x3 MG LF LG La <lig>MG Md</lig> c ______ {staf: 5} {clef: C10} {solm: 0} <lig><obl>Bb BG</obl> Ba <label>em-</label></lig> -LD LG -ME <lig>SF SG</lig> c __ {staf: 5} {clef: C10} {solm: 0} Sa Bb Bc <label>   plum.</label> Bd Sc <lig><obl>Sb SG</obl> Ba <label>{red}§</label></lig> LG |_ </example>\n\
[-171ra-] <red>Octava regula generalis. §</red>\n\
<2line>[O]</2line>{redline}Ctava regula generalis est quod omnis nota ternario numero subiecta est alterabilis. {redline}Unde cum longa in modo maiori perfecto. {redline}Brevis in modo minori imperfecto. {redline}Semibrevis in tempore perfecto, {redline}Et minima in prolatione maiori, numero ternario sint subiecte, in ipsis quantitatibus veniunt alterande. de quarum quidem alterationibus ut clarius intelligantur particulariter tractabimus</chapter>\n\
<chapter> <red>De alteratione longe Capitulum 2^m. -</red>\n\
<2line>[S]**Cue letter ‘ſ’ for the missing initial written in the centre of the upper line of the empty space, very small with a fine pen in a 15th-century hand.**</2line>{redline}I due longe sole, in modo maiori perfecto ante maximam inveniantur ultima earum alteratur ut in, exemplo sequenti.\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} <label>{red}¶ {redline}Ex-</label> {solm: 0} _{mens: O7}PL5-9x3 -MD <lig>LG La</lig> MG<label> em-  {red}-</label>. La Mb. c ______ {staf: 5} _{clef: C10} {solm: 0} Lc Md <lig>LG La Lb <label>plum.</label></lig> <lig>Lc La</lig> MG ||<label>{red}§</label>_{red}| [-] </example>\n\
<red>De alteratione brevis Capitulum 3^m.</red>\n\
<2line>[S]</2line>{redline}I due breves sole in modo minori perfecto ante longam aut eius pausam inveniantur ultima illarum alteratur. ut patet in exemplo subsequenti.\n\
[2 blank lines]\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: C11} PL5-9x3 <label>  {red}¶{redline}Ex-</label> <lig><obl>BG BE</obl></lig> -LD <lig>BE BF</lig> PL5-9 LG Ba. c _ [-171rb-] {staf: 5} _{clef: C10} {solm: 0} <lig><obl>BF BE</obl></lig> BD <lig>BF <label> em-</label> BG</lig> <lig>La Bd</lig>. <lig>BG Ba BF BG Ba</lig> PL7-11 c __ {staf: 5} _{clef: C10} {solm: 0} Ld <label>  plum.</label> <lig>BG <obl>Bb BG</obl></lig> LG ||_{red}| <label><red>§ -  § -</red></label> [-][-][-][-] </example>\n\
<red>De alteratione semibrevis.</red>\n\
<2line>[S]</2line>{redline}I due semibreves sole, in tempore perfecto ante brevem, aut eius pausam inveniantur ultima illarum alteratur ut patet in exemplo subsequenti.[.]<red>-[.]§[.]-[.]§</red>\n\
<example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: Ø11}PL9-11 Bd <label>{redline}Ex-</label> <lig><obl>Sb Sa</obl></lig> BG <lig>Sa Sb</lig> PB9 BG. Sa c _ {staf: 5} _{clef: C10} {solm: 0} BF. SE <lig>BD Ba</lig> <lig><label>em-</label> SG Sa</lig> Sb <lig><obl>Sc Sb</obl></lig> Ba <lig>SG <label>{red}-</label> Sa</lig> c __ {staf: 5} _{clef: C10} {solm: 0} Sb <lig>Sc Sd <label>plum.</label></lig> PB9 <lig>BG Ba</lig> MG ||_{red}| [-][-]<label>{red}§</label>[-][-] </example>\n\
<red>De alteratione minime-.</red>\n\
<2line>[S]</2line>{redline}I due minime sole in maiori prolatione ante semibrevem aut eius pausam inveniantur ultima illarum alteratur ut in exemplo subsequenti patet.[-]{red}¶{redline}Verte. <marg: fore (right) foot><newhand: B>B3</newhand></marg>\n\
[-171va-] <example: {column measure}, {mensural: void}, {staf: 5, black}> _{clef: C10} {solm: 0} {mens: Ç5}PL5-7 <label>{red}¶ {redline}Ex</label> SD mE mF <lig>SG Sa</lig> mb mc PS9 Sd mc<label>{red}-</label>. ma mb c _____ {staf: 5} _{clef: C10} {solm: 0} mc -md mG Sa <label>em-</label> mD mF mE mD mF PS5 SG <label>  {red}-</label> <lig>Sa Sb</lig> c ____ {staf: 5} _{clef: C10} {solm: 0} Sc -md. mb mG <label> plum.   <red>§   -   §</red></label> Sa mc. mb Sa LG || [-][-] </example></chapter>\n\
<explicit> {red}¶ {redline}Explicit tractatulus de alterationibus notarum.</explicit></treatise>';
